#!groovy

pipeline {

    agent {
        label 'master'
    }

    environment {
        HOST_NAME = "172.28.198.1"
        GROUP = "deployuser"
        CREDENTIAL_GIT = "6e46ff20-e4dc-4caa-863f-a59fa1888b7d"
        EMAIL = 'macro-devops@globant.com'
        DEFAULT_SUBJECT = "Jenkins Support Biometria Commons "
        POM_VERSION = readMavenPom().getVersion()
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }

    stages {
        stage('Clone') {

            steps {
                echo 'Clone'
            }
        }
        stage('Test') {

            steps {
                withMaven {
                    sh "mvn clean compile test"
                }
            }
        }

        stage('Coverage') {
            steps {
                script {
                    env.scannerHome = tool name: 'SonarQube Scanner'
                }
                sh "${scannerHome}/bin/sonar-scanner -Dsonar.projectVersion=${POM_VERSION}"
            }
        }

        stage('Construct') {
            steps {
                echo 'Build Notification Service Jar'
                withMaven {
                    sh "mvn clean source:jar install -Dmaven.test.skip=true -Djenkins.build.number=${env.BUILD_NUMBER}"
                }
            }
        }

        stage('Deploy') {
            steps {
                withMaven {
                    echo "Deploy Nexus"
                    sh "mvn clean deploy"

                }
            }
        }

    }
}