//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.30 at 12:06:50 PM COT 
//


package ar.com.macro.enrolamiento.model.client.daonengine.dto.soap;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * Base type for ordered list Requests.
 * 					
 * 
 * <p>Java class for AbstractOrderedListRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractOrderedListRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.daon.com/ws/de}AbstractListRequest"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ReturnSetOrder" type="{http://www.daon.com/ws/de}ReturnSetOrder" minOccurs="0"/&gt;
 *         &lt;element name="OrderByField" type="{http://www.daon.com/ws/de}Field" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractOrderedListRequest", propOrder = {
    "returnSetOrder",
    "orderByField"
})
@XmlSeeAlso({
    ListIdentitiesRequest.class
})
public abstract class AbstractOrderedListRequest
    extends AbstractListRequest
{

    @XmlElement(name = "ReturnSetOrder", defaultValue = "ASC")
    @XmlSchemaType(name = "string")
    protected ReturnSetOrder returnSetOrder;
    @XmlElement(name = "OrderByField")
    protected List<String> orderByField;

    /**
     * Gets the value of the returnSetOrder property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnSetOrder }
     *     
     */
    public ReturnSetOrder getReturnSetOrder() {
        return returnSetOrder;
    }

    /**
     * Sets the value of the returnSetOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnSetOrder }
     *     
     */
    public void setReturnSetOrder(ReturnSetOrder value) {
        this.returnSetOrder = value;
    }

    /**
     * Gets the value of the orderByField property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderByField property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderByField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOrderByField() {
        if (orderByField == null) {
            orderByField = new ArrayList<String>();
        }
        return this.orderByField;
    }

}
