//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.30 at 12:06:50 PM COT 
//


package ar.com.macro.enrolamiento.model.client.daonengine.dto.soap;

import javax.xml.bind.annotation.*;


/**
 * Request a description of all data associated
 * 							with
 * 							the given Identity.
 * 						
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.daon.com/ws/de}AbstractRequest"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DomainIdentifier" type="{http://www.daon.com/ws/de}DomainIdentifier"/&gt;
 *         &lt;element name="IdentityIdentifier" type="{http://www.daon.com/ws/de}IdentityIdentifier"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "domainIdentifier",
    "identityIdentifier"
})
@XmlRootElement(name = "GetIdentityDescriptionRequest")
public class GetIdentityDescriptionRequest
    extends AbstractRequest
{

    @XmlElement(name = "DomainIdentifier", required = true)
    protected DomainIdentifier domainIdentifier;
    @XmlElement(name = "IdentityIdentifier", required = true)
    protected IdentityIdentifier identityIdentifier;

    /**
     * Gets the value of the domainIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link DomainIdentifier }
     *     
     */
    public DomainIdentifier getDomainIdentifier() {
        return domainIdentifier;
    }

    /**
     * Sets the value of the domainIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainIdentifier }
     *     
     */
    public void setDomainIdentifier(DomainIdentifier value) {
        this.domainIdentifier = value;
    }

    /**
     * Gets the value of the identityIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityIdentifier }
     *     
     */
    public IdentityIdentifier getIdentityIdentifier() {
        return identityIdentifier;
    }

    /**
     * Sets the value of the identityIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityIdentifier }
     *     
     */
    public void setIdentityIdentifier(IdentityIdentifier value) {
        this.identityIdentifier = value;
    }

}
