//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.30 at 12:06:50 PM COT 
//


package ar.com.macro.enrolamiento.model.client.daonengine.dto.soap;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ar.com.macro.service.daonengine.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Binary_QNAME = new QName("http://www.daon.com/de/metadata", "Binary");
    private final static QName _NameValuePair_QNAME = new QName("http://www.daon.com/de/metadata", "NameValuePair");
    private final static QName _Boolean_QNAME = new QName("http://www.daon.com/de/metadata", "Boolean");
    private final static QName _DataTime_QNAME = new QName("http://www.daon.com/de/metadata", "DataTime");
    private final static QName _Date_QNAME = new QName("http://www.daon.com/de/metadata", "Date");
    private final static QName _Double_QNAME = new QName("http://www.daon.com/de/metadata", "Double");
    private final static QName _Integer_QNAME = new QName("http://www.daon.com/de/metadata", "Integer");
    private final static QName _MetaData_QNAME = new QName("http://www.daon.com/de/metadata", "MetaData");
    private final static QName _MetaDataItem_QNAME = new QName("http://www.daon.com/de/metadata", "MetaDataItem");
    private final static QName _Nested_QNAME = new QName("http://www.daon.com/de/metadata", "Nested");
    private final static QName _OptionalNestedNameValuePair_QNAME = new QName("http://www.daon.com/de/metadata", "OptionalNestedNameValuePair");
    private final static QName _String_QNAME = new QName("http://www.daon.com/de/metadata", "String");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ar.com.macro.service.daonengine.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateIdentitiesRequest }
     * 
     */
    public CreateIdentitiesRequest createCreateIdentitiesRequest() {
        return new CreateIdentitiesRequest();
    }

    /**
     * Create an instance of {@link CreateIdentitiesResponse }
     * 
     */
    public CreateIdentitiesResponse createCreateIdentitiesResponse() {
        return new CreateIdentitiesResponse();
    }

    /**
     * Create an instance of {@link CreateIdentityResponse }
     * 
     */
    public CreateIdentityResponse createCreateIdentityResponse() {
        return new CreateIdentityResponse();
    }

    /**
     * Create an instance of {@link DeleteIdentitiesRequest }
     * 
     */
    public DeleteIdentitiesRequest createDeleteIdentitiesRequest() {
        return new DeleteIdentitiesRequest();
    }

    /**
     * Create an instance of {@link GetIdentitiesResponse }
     * 
     */
    public GetIdentitiesResponse createGetIdentitiesResponse() {
        return new GetIdentitiesResponse();
    }

    /**
     * Create an instance of {@link GetIdentityCountResponse }
     * 
     */
    public GetIdentityCountResponse createGetIdentityCountResponse() {
        return new GetIdentityCountResponse();
    }

    /**
     * Create an instance of {@link GetIdentityDescriptionResponse }
     * 
     */
    public GetIdentityDescriptionResponse createGetIdentityDescriptionResponse() {
        return new GetIdentityDescriptionResponse();
    }

    /**
     * Create an instance of {@link GetIdentityResponse }
     * 
     */
    public GetIdentityResponse createGetIdentityResponse() {
        return new GetIdentityResponse();
    }

    /**
     * Create an instance of {@link ListIdentitiesResponse }
     * 
     */
    public ListIdentitiesResponse createListIdentitiesResponse() {
        return new ListIdentitiesResponse();
    }

    /**
     * Create an instance of {@link UpdateIdentitiesRequest }
     * 
     */
    public UpdateIdentitiesRequest createUpdateIdentitiesRequest() {
        return new UpdateIdentitiesRequest();
    }

    /**
     * Create an instance of {@link BiometricDataElement }
     * 
     */
    public BiometricDataElement createBiometricDataElement() {
        return new BiometricDataElement();
    }

    /**
     * Create an instance of {@link GenericRequestParameters }
     * 
     */
    public GenericRequestParameters createGenericRequestParameters() {
        return new GenericRequestParameters();
    }

    /**
     * Create an instance of {@link CustomParameters }
     * 
     */
    public CustomParameters createCustomParameters() {
        return new CustomParameters();
    }

    /**
     * Create an instance of {@link CreateIdentitiesRequest.DomainCreate }
     * 
     */
    public CreateIdentitiesRequest.DomainCreate createCreateIdentitiesRequestDomainCreate() {
        return new CreateIdentitiesRequest.DomainCreate();
    }

    /**
     * Create an instance of {@link ResponseStatus }
     * 
     */
    public ResponseStatus createResponseStatus() {
        return new ResponseStatus();
    }

    /**
     * Create an instance of {@link CreateIdentitiesResponse.ResponseData }
     * 
     */
    public CreateIdentitiesResponse.ResponseData createCreateIdentitiesResponseResponseData() {
        return new CreateIdentitiesResponse.ResponseData();
    }

    /**
     * Create an instance of {@link CreateIdentityRequest }
     * 
     */
    public CreateIdentityRequest createCreateIdentityRequest() {
        return new CreateIdentityRequest();
    }

    /**
     * Create an instance of {@link DomainIdentifier }
     * 
     */
    public DomainIdentifier createDomainIdentifier() {
        return new DomainIdentifier();
    }

    /**
     * Create an instance of {@link PolicyIdentifier }
     * 
     */
    public PolicyIdentifier createPolicyIdentifier() {
        return new PolicyIdentifier();
    }

    /**
     * Create an instance of {@link Identity }
     * 
     */
    public Identity createIdentity() {
        return new Identity();
    }

    /**
     * Create an instance of {@link CreateIdentityResponse.ResponseData }
     * 
     */
    public CreateIdentityResponse.ResponseData createCreateIdentityResponseResponseData() {
        return new CreateIdentityResponse.ResponseData();
    }

    /**
     * Create an instance of {@link DeleteIdentitiesRequest.DomainDelete }
     * 
     */
    public DeleteIdentitiesRequest.DomainDelete createDeleteIdentitiesRequestDomainDelete() {
        return new DeleteIdentitiesRequest.DomainDelete();
    }

    /**
     * Create an instance of {@link DeleteIdentitiesResponse }
     * 
     */
    public DeleteIdentitiesResponse createDeleteIdentitiesResponse() {
        return new DeleteIdentitiesResponse();
    }

    /**
     * Create an instance of {@link DeleteIdentityRequest }
     * 
     */
    public DeleteIdentityRequest createDeleteIdentityRequest() {
        return new DeleteIdentityRequest();
    }

    /**
     * Create an instance of {@link IdentityIdentifier }
     * 
     */
    public IdentityIdentifier createIdentityIdentifier() {
        return new IdentityIdentifier();
    }

    /**
     * Create an instance of {@link DeleteIdentityResponse }
     * 
     */
    public DeleteIdentityResponse createDeleteIdentityResponse() {
        return new DeleteIdentityResponse();
    }

    /**
     * Create an instance of {@link GetIdentitiesRequest }
     * 
     */
    public GetIdentitiesRequest createGetIdentitiesRequest() {
        return new GetIdentitiesRequest();
    }

    /**
     * Create an instance of {@link IdentityDataFilter }
     * 
     */
    public IdentityDataFilter createIdentityDataFilter() {
        return new IdentityDataFilter();
    }

    /**
     * Create an instance of {@link GetIdentitiesResponse.ResponseData }
     * 
     */
    public GetIdentitiesResponse.ResponseData createGetIdentitiesResponseResponseData() {
        return new GetIdentitiesResponse.ResponseData();
    }

    /**
     * Create an instance of {@link GetIdentityCountRequest }
     * 
     */
    public GetIdentityCountRequest createGetIdentityCountRequest() {
        return new GetIdentityCountRequest();
    }

    /**
     * Create an instance of {@link GetIdentityCountResponse.ResponseData }
     * 
     */
    public GetIdentityCountResponse.ResponseData createGetIdentityCountResponseResponseData() {
        return new GetIdentityCountResponse.ResponseData();
    }

    /**
     * Create an instance of {@link GetIdentityDescriptionRequest }
     * 
     */
    public GetIdentityDescriptionRequest createGetIdentityDescriptionRequest() {
        return new GetIdentityDescriptionRequest();
    }

    /**
     * Create an instance of {@link GetIdentityDescriptionResponse.ResponseData }
     * 
     */
    public GetIdentityDescriptionResponse.ResponseData createGetIdentityDescriptionResponseResponseData() {
        return new GetIdentityDescriptionResponse.ResponseData();
    }

    /**
     * Create an instance of {@link GetIdentityRequest }
     * 
     */
    public GetIdentityRequest createGetIdentityRequest() {
        return new GetIdentityRequest();
    }

    /**
     * Create an instance of {@link GetIdentityResponse.ResponseData }
     * 
     */
    public GetIdentityResponse.ResponseData createGetIdentityResponseResponseData() {
        return new GetIdentityResponse.ResponseData();
    }

    /**
     * Create an instance of {@link ListIdentitiesRequest }
     * 
     */
    public ListIdentitiesRequest createListIdentitiesRequest() {
        return new ListIdentitiesRequest();
    }

    /**
     * Create an instance of {@link ReturnSetCriteria }
     * 
     */
    public ReturnSetCriteria createReturnSetCriteria() {
        return new ReturnSetCriteria();
    }

    /**
     * Create an instance of {@link ListIdentitiesResponse.ResponseData }
     * 
     */
    public ListIdentitiesResponse.ResponseData createListIdentitiesResponseResponseData() {
        return new ListIdentitiesResponse.ResponseData();
    }

    /**
     * Create an instance of {@link UpdateIdentitiesRequest.DomainUpdate }
     * 
     */
    public UpdateIdentitiesRequest.DomainUpdate createUpdateIdentitiesRequestDomainUpdate() {
        return new UpdateIdentitiesRequest.DomainUpdate();
    }

    /**
     * Create an instance of {@link UpdateIdentitiesResponse }
     * 
     */
    public UpdateIdentitiesResponse createUpdateIdentitiesResponse() {
        return new UpdateIdentitiesResponse();
    }

    /**
     * Create an instance of {@link UpdateIdentityRequest }
     * 
     */
    public UpdateIdentityRequest createUpdateIdentityRequest() {
        return new UpdateIdentityRequest();
    }

    /**
     * Create an instance of {@link IdentityDescription }
     * 
     */
    public IdentityDescription createIdentityDescription() {
        return new IdentityDescription();
    }

    /**
     * Create an instance of {@link UpdateIdentityResponse }
     * 
     */
    public UpdateIdentityResponse createUpdateIdentityResponse() {
        return new UpdateIdentityResponse();
    }

    /**
     * Create an instance of {@link BiographicData }
     * 
     */
    public BiographicData createBiographicData() {
        return new BiographicData();
    }

    /**
     * Create an instance of {@link BiographicDataInfo }
     * 
     */
    public BiographicDataInfo createBiographicDataInfo() {
        return new BiographicDataInfo();
    }

    /**
     * Create an instance of {@link BiographicFilter }
     * 
     */
    public BiographicFilter createBiographicFilter() {
        return new BiographicFilter();
    }

    /**
     * Create an instance of {@link BiometricFilter }
     * 
     */
    public BiometricFilter createBiometricFilter() {
        return new BiometricFilter();
    }

    /**
     * Create an instance of {@link BiometricItemInfo }
     * 
     */
    public BiometricItemInfo createBiometricItemInfo() {
        return new BiometricItemInfo();
    }

    /**
     * Create an instance of {@link CoreData }
     * 
     */
    public CoreData createCoreData() {
        return new CoreData();
    }

    /**
     * Create an instance of {@link DateItem }
     * 
     */
    public DateItem createDateItem() {
        return new DateItem();
    }

    /**
     * Create an instance of {@link DateItemInfo }
     * 
     */
    public DateItemInfo createDateItemInfo() {
        return new DateItemInfo();
    }

    /**
     * Create an instance of {@link DoubleItem }
     * 
     */
    public DoubleItem createDoubleItem() {
        return new DoubleItem();
    }

    /**
     * Create an instance of {@link DoubleItemInfo }
     * 
     */
    public DoubleItemInfo createDoubleItemInfo() {
        return new DoubleItemInfo();
    }

    /**
     * Create an instance of {@link ExclusiveBiographicDataFilter }
     * 
     */
    public ExclusiveBiographicDataFilter createExclusiveBiographicDataFilter() {
        return new ExclusiveBiographicDataFilter();
    }

    /**
     * Create an instance of {@link ExclusiveBiometricDataFilter }
     * 
     */
    public ExclusiveBiometricDataFilter createExclusiveBiometricDataFilter() {
        return new ExclusiveBiometricDataFilter();
    }

    /**
     * Create an instance of {@link ExtendedBinaryItem }
     * 
     */
    public ExtendedBinaryItem createExtendedBinaryItem() {
        return new ExtendedBinaryItem();
    }

    /**
     * Create an instance of {@link ExtendedBinaryItemInfo }
     * 
     */
    public ExtendedBinaryItemInfo createExtendedBinaryItemInfo() {
        return new ExtendedBinaryItemInfo();
    }

    /**
     * Create an instance of {@link ExtendedStringItem }
     * 
     */
    public ExtendedStringItem createExtendedStringItem() {
        return new ExtendedStringItem();
    }

    /**
     * Create an instance of {@link ExtendedStringItemInfo }
     * 
     */
    public ExtendedStringItemInfo createExtendedStringItemInfo() {
        return new ExtendedStringItemInfo();
    }

    /**
     * Create an instance of {@link GroupIdentifier }
     * 
     */
    public GroupIdentifier createGroupIdentifier() {
        return new GroupIdentifier();
    }

    /**
     * Create an instance of {@link GroupMembership }
     * 
     */
    public GroupMembership createGroupMembership() {
        return new GroupMembership();
    }

    /**
     * Create an instance of {@link IncludeAllBiographicDataFilter }
     * 
     */
    public IncludeAllBiographicDataFilter createIncludeAllBiographicDataFilter() {
        return new IncludeAllBiographicDataFilter();
    }

    /**
     * Create an instance of {@link IncludeAllBiometricDataFilter }
     * 
     */
    public IncludeAllBiometricDataFilter createIncludeAllBiometricDataFilter() {
        return new IncludeAllBiometricDataFilter();
    }

    /**
     * Create an instance of {@link InclusiveBiographicDataFilter }
     * 
     */
    public InclusiveBiographicDataFilter createInclusiveBiographicDataFilter() {
        return new InclusiveBiographicDataFilter();
    }

    /**
     * Create an instance of {@link InclusiveBiometricDataFilter }
     * 
     */
    public InclusiveBiometricDataFilter createInclusiveBiometricDataFilter() {
        return new InclusiveBiometricDataFilter();
    }

    /**
     * Create an instance of {@link Key }
     * 
     */
    public Key createKey() {
        return new Key();
    }

    /**
     * Create an instance of {@link KeyIdentifier }
     * 
     */
    public KeyIdentifier createKeyIdentifier() {
        return new KeyIdentifier();
    }

    /**
     * Create an instance of {@link LongItem }
     * 
     */
    public LongItem createLongItem() {
        return new LongItem();
    }

    /**
     * Create an instance of {@link LongItemInfo }
     * 
     */
    public LongItemInfo createLongItemInfo() {
        return new LongItemInfo();
    }

    /**
     * Create an instance of {@link Policy }
     * 
     */
    public Policy createPolicy() {
        return new Policy();
    }

    /**
     * Create an instance of {@link PolicyDescription }
     * 
     */
    public PolicyDescription createPolicyDescription() {
        return new PolicyDescription();
    }

    /**
     * Create an instance of {@link PolicyDetails }
     * 
     */
    public PolicyDetails createPolicyDetails() {
        return new PolicyDetails();
    }

    /**
     * Create an instance of {@link SecureEnvelope }
     * 
     */
    public SecureEnvelope createSecureEnvelope() {
        return new SecureEnvelope();
    }

    /**
     * Create an instance of {@link StringItem }
     * 
     */
    public StringItem createStringItem() {
        return new StringItem();
    }

    /**
     * Create an instance of {@link StringItemInfo }
     * 
     */
    public StringItemInfo createStringItemInfo() {
        return new StringItemInfo();
    }

    /**
     * Create an instance of {@link TimestampItem }
     * 
     */
    public TimestampItem createTimestampItem() {
        return new TimestampItem();
    }

    /**
     * Create an instance of {@link TimestampItemInfo }
     * 
     */
    public TimestampItemInfo createTimestampItemInfo() {
        return new TimestampItemInfo();
    }

    /**
     * Create an instance of {@link BinaryNameValuePair }
     * 
     */
    public BinaryNameValuePair createBinaryNameValuePair() {
        return new BinaryNameValuePair();
    }

    /**
     * Create an instance of {@link BooleanNameValuePair }
     * 
     */
    public BooleanNameValuePair createBooleanNameValuePair() {
        return new BooleanNameValuePair();
    }

    /**
     * Create an instance of {@link DateTimeNameValuePair }
     * 
     */
    public DateTimeNameValuePair createDateTimeNameValuePair() {
        return new DateTimeNameValuePair();
    }

    /**
     * Create an instance of {@link DateNameValuePair }
     * 
     */
    public DateNameValuePair createDateNameValuePair() {
        return new DateNameValuePair();
    }

    /**
     * Create an instance of {@link DoubleNameValuePair }
     * 
     */
    public DoubleNameValuePair createDoubleNameValuePair() {
        return new DoubleNameValuePair();
    }

    /**
     * Create an instance of {@link IntegerNameValuePair }
     * 
     */
    public IntegerNameValuePair createIntegerNameValuePair() {
        return new IntegerNameValuePair();
    }

    /**
     * Create an instance of {@link MetaData }
     * 
     */
    public MetaData createMetaData() {
        return new MetaData();
    }

    /**
     * Create an instance of {@link MetaDataItem }
     * 
     */
    public MetaDataItem createMetaDataItem() {
        return new MetaDataItem();
    }

    /**
     * Create an instance of {@link NestedNameValuePair }
     * 
     */
    public NestedNameValuePair createNestedNameValuePair() {
        return new NestedNameValuePair();
    }

    /**
     * Create an instance of {@link OptionalNestedNameValuePair }
     * 
     */
    public OptionalNestedNameValuePair createOptionalNestedNameValuePair() {
        return new OptionalNestedNameValuePair();
    }

    /**
     * Create an instance of {@link StringNameValuePair }
     * 
     */
    public StringNameValuePair createStringNameValuePair() {
        return new StringNameValuePair();
    }

    /**
     * Create an instance of {@link BiometricDataElement.Data }
     * 
     */
    public BiometricDataElement.Data createBiometricDataElementData() {
        return new BiometricDataElement.Data();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BinaryNameValuePair }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BinaryNameValuePair }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/de/metadata", name = "Binary", substitutionHeadNamespace = "http://www.daon.com/de/metadata", substitutionHeadName = "NameValuePair")
    public JAXBElement<BinaryNameValuePair> createBinary(BinaryNameValuePair value) {
        return new JAXBElement<BinaryNameValuePair>(_Binary_QNAME, BinaryNameValuePair.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameValuePair }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NameValuePair }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/de/metadata", name = "NameValuePair")
    public JAXBElement<NameValuePair> createNameValuePair(NameValuePair value) {
        return new JAXBElement<NameValuePair>(_NameValuePair_QNAME, NameValuePair.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BooleanNameValuePair }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BooleanNameValuePair }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/de/metadata", name = "Boolean", substitutionHeadNamespace = "http://www.daon.com/de/metadata", substitutionHeadName = "NameValuePair")
    public JAXBElement<BooleanNameValuePair> createBoolean(BooleanNameValuePair value) {
        return new JAXBElement<BooleanNameValuePair>(_Boolean_QNAME, BooleanNameValuePair.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateTimeNameValuePair }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DateTimeNameValuePair }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/de/metadata", name = "DataTime", substitutionHeadNamespace = "http://www.daon.com/de/metadata", substitutionHeadName = "NameValuePair")
    public JAXBElement<DateTimeNameValuePair> createDataTime(DateTimeNameValuePair value) {
        return new JAXBElement<DateTimeNameValuePair>(_DataTime_QNAME, DateTimeNameValuePair.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateNameValuePair }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DateNameValuePair }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/de/metadata", name = "Date", substitutionHeadNamespace = "http://www.daon.com/de/metadata", substitutionHeadName = "NameValuePair")
    public JAXBElement<DateNameValuePair> createDate(DateNameValuePair value) {
        return new JAXBElement<DateNameValuePair>(_Date_QNAME, DateNameValuePair.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DoubleNameValuePair }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DoubleNameValuePair }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/de/metadata", name = "Double", substitutionHeadNamespace = "http://www.daon.com/de/metadata", substitutionHeadName = "NameValuePair")
    public JAXBElement<DoubleNameValuePair> createDouble(DoubleNameValuePair value) {
        return new JAXBElement<DoubleNameValuePair>(_Double_QNAME, DoubleNameValuePair.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IntegerNameValuePair }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link IntegerNameValuePair }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/de/metadata", name = "Integer", substitutionHeadNamespace = "http://www.daon.com/de/metadata", substitutionHeadName = "NameValuePair")
    public JAXBElement<IntegerNameValuePair> createInteger(IntegerNameValuePair value) {
        return new JAXBElement<IntegerNameValuePair>(_Integer_QNAME, IntegerNameValuePair.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetaData }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MetaData }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/de/metadata", name = "MetaData")
    public JAXBElement<MetaData> createMetaData(MetaData value) {
        return new JAXBElement<MetaData>(_MetaData_QNAME, MetaData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetaDataItem }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MetaDataItem }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/de/metadata", name = "MetaDataItem")
    public JAXBElement<MetaDataItem> createMetaDataItem(MetaDataItem value) {
        return new JAXBElement<MetaDataItem>(_MetaDataItem_QNAME, MetaDataItem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NestedNameValuePair }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NestedNameValuePair }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/de/metadata", name = "Nested", substitutionHeadNamespace = "http://www.daon.com/de/metadata", substitutionHeadName = "NameValuePair")
    public JAXBElement<NestedNameValuePair> createNested(NestedNameValuePair value) {
        return new JAXBElement<NestedNameValuePair>(_Nested_QNAME, NestedNameValuePair.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionalNestedNameValuePair }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OptionalNestedNameValuePair }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/de/metadata", name = "OptionalNestedNameValuePair")
    public JAXBElement<OptionalNestedNameValuePair> createOptionalNestedNameValuePair(OptionalNestedNameValuePair value) {
        return new JAXBElement<OptionalNestedNameValuePair>(_OptionalNestedNameValuePair_QNAME, OptionalNestedNameValuePair.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringNameValuePair }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StringNameValuePair }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/de/metadata", name = "String", substitutionHeadNamespace = "http://www.daon.com/de/metadata", substitutionHeadName = "NameValuePair")
    public JAXBElement<StringNameValuePair> createString(StringNameValuePair value) {
        return new JAXBElement<StringNameValuePair>(_String_QNAME, StringNameValuePair.class, null, value);
    }

}
