version: "3.9"
    
services:
  mysql:
    image: mysql:5.7.35
    container_name: biometria-db
    hostname: biometria-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_macro_biometrics
      MYSQL_USER: sa
      MYSQL_PASSWORD: Globant2021*
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306