//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.08 at 01:37:27 PM PET 
//


package ar.com.macro.validacion.model.client.renaper.dto.soap;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for generarTransaccion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="generarTransaccion"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="entrada" type="{urn:mininteriorwsdl}entrada"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "generarTransaccion", propOrder = {

})
@XmlRootElement(name = "generarTransaccion")

public class GenerarTransaccion {

    @XmlElement(required = true)
    protected Entrada entrada;

    /**
     * Gets the value of the entrada property.
     * 
     * @return
     *     possible object is
     *     {@link Entrada }
     *     
     */
    public Entrada getEntrada() {
        return entrada;
    }

    /**
     * Sets the value of the entrada property.
     * 
     * @param value
     *     allowed object is
     *     {@link Entrada }
     *     
     */
    public void setEntrada(Entrada value) {
        this.entrada = value;
    }

}
