//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.08 at 01:37:27 PM PET 
//


package ar.com.macro.validacion.model.client.renaper.dto.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mininteriorwsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mininteriorwsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Entrada }
     * 
     */
    public Entrada createEntrada() {
        return new Entrada();
    }

    /**
     * Create an instance of {@link Salida }
     * 
     */
    public Salida createSalida() {
        return new Salida();
    }

    /**
     * Create an instance of {@link GenerarTransaccion }
     * 
     */
    public GenerarTransaccion createGenerarTransaccion() {
        return new GenerarTransaccion();
    }

    /**
     * Create an instance of {@link GenerarTransaccionResponse }
     * 
     */
    public GenerarTransaccionResponse createGenerarTransaccionResponse() {
        return new GenerarTransaccionResponse();
    }

    /**
     * Create an instance of {@link ConsultaPorTCN }
     * 
     */
    public ConsultaPorTCN createConsultaPorTCN() {
        return new ConsultaPorTCN();
    }

    /**
     * Create an instance of {@link ConsultaPorTCNResponse }
     * 
     */
    public ConsultaPorTCNResponse createConsultaPorTCNResponse() {
        return new ConsultaPorTCNResponse();
    }

}
