//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.08 at 01:37:27 PM PET 
//


package ar.com.macro.validacion.model.client.renaper.dto.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for salida complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="salida"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="transactionControlNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="transactionControlReference" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dateOfTransaction" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="matchScore" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="matchType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="codigo" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="mensaje" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "salida", propOrder = {

})
public class Salida {

    @XmlElement(required = true)
    protected String transactionControlNumber;
    @XmlElement(required = true)
    protected String transactionControlReference;
    @XmlElement(required = true)
    protected String dateOfTransaction;
    @XmlElement(required = true)
    protected String matchScore;
    @XmlElement(required = true)
    protected String matchType;
    protected int codigo;
    @XmlElement(required = true)
    protected String mensaje;

    /**
     * Gets the value of the transactionControlNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionControlNumber() {
        return transactionControlNumber;
    }

    /**
     * Sets the value of the transactionControlNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionControlNumber(String value) {
        this.transactionControlNumber = value;
    }

    /**
     * Gets the value of the transactionControlReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionControlReference() {
        return transactionControlReference;
    }

    /**
     * Sets the value of the transactionControlReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionControlReference(String value) {
        this.transactionControlReference = value;
    }

    /**
     * Gets the value of the dateOfTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfTransaction() {
        return dateOfTransaction;
    }

    /**
     * Sets the value of the dateOfTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfTransaction(String value) {
        this.dateOfTransaction = value;
    }

    /**
     * Gets the value of the matchScore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatchScore() {
        return matchScore;
    }

    /**
     * Sets the value of the matchScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatchScore(String value) {
        this.matchScore = value;
    }

    /**
     * Gets the value of the matchType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatchType() {
        return matchType;
    }

    /**
     * Sets the value of the matchType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatchType(String value) {
        this.matchType = value;
    }

    /**
     * Gets the value of the codigo property.
     * 
     */
    public int getCodigo() {
        return codigo;
    }

    /**
     * Sets the value of the codigo property.
     * 
     */
    public void setCodigo(int value) {
        this.codigo = value;
    }

    /**
     * Gets the value of the mensaje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMensaje() {
        return mensaje;
    }

    /**
     * Sets the value of the mensaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMensaje(String value) {
        this.mensaje = value;
    }

}
