//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.30 at 12:06:50 PM COT 
//


package ar.com.macro.validacion.model.client.daonengine.dto.soap;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Base type for extended items.
 * 					
 * 
 * <p>Java class for AbstractExtendedItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractExtendedItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.daon.com/ws/de}AbstractBiographicItem"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SubType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UpdatedDtm" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="ApplicationIdentifier" type="{http://www.daon.com/ws/de}ApplicationIdentifier" minOccurs="0"/&gt;
 *         &lt;element name="ApplicationUserIdentifier" type="{http://www.daon.com/ws/de}ApplicationUserIdentifier" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractExtendedItem", propOrder = {
    "subType",
    "updatedDtm",
    "applicationIdentifier",
    "applicationUserIdentifier"
})
@XmlSeeAlso({
    ExtendedBinaryItem.class,
    ExtendedStringItem.class
})
public abstract class AbstractExtendedItem
    extends AbstractBiographicItem
{

    @XmlElement(name = "SubType")
    protected String subType;
    @XmlElement(name = "UpdatedDtm")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updatedDtm;
    @XmlElement(name = "ApplicationIdentifier")
    protected String applicationIdentifier;
    @XmlElement(name = "ApplicationUserIdentifier")
    protected String applicationUserIdentifier;

    /**
     * Gets the value of the subType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubType() {
        return subType;
    }

    /**
     * Sets the value of the subType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubType(String value) {
        this.subType = value;
    }

    /**
     * Gets the value of the updatedDtm property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdatedDtm() {
        return updatedDtm;
    }

    /**
     * Sets the value of the updatedDtm property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdatedDtm(XMLGregorianCalendar value) {
        this.updatedDtm = value;
    }

    /**
     * Gets the value of the applicationIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationIdentifier() {
        return applicationIdentifier;
    }

    /**
     * Sets the value of the applicationIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationIdentifier(String value) {
        this.applicationIdentifier = value;
    }

    /**
     * Gets the value of the applicationUserIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationUserIdentifier() {
        return applicationUserIdentifier;
    }

    /**
     * Sets the value of the applicationUserIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationUserIdentifier(String value) {
        this.applicationUserIdentifier = value;
    }

}
