//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.30 at 12:06:50 PM COT 
//


package ar.com.macro.validacion.model.client.daonengine.dto.soap;

import javax.xml.bind.annotation.*;


/**
 * Base type for Requests.
 * 
 * <p>Java class for AbstractRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GenericRequestParameters" type="{http://www.daon.com/ws/de}GenericRequestParameters"/&gt;
 *         &lt;element name="CustomParameters" type="{http://www.daon.com/ws/de}CustomParameters" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractRequest", propOrder = {
    "genericRequestParameters",
    "customParameters"
})
@XmlSeeAlso({
    UpdateIdentityRequest.class,
    UpdateIdentitiesRequest.class,
    AbstractListRequest.class,
    GetIdentityRequest.class,
    GetIdentityDescriptionRequest.class,
    GetIdentityCountRequest.class,
    GetIdentitiesRequest.class,
    DeleteIdentityRequest.class,
    DeleteIdentitiesRequest.class,
    CreateIdentityRequest.class,
    CreateIdentitiesRequest.class
})
public abstract class AbstractRequest {

    @XmlElement(name = "GenericRequestParameters", required = true)
    protected GenericRequestParameters genericRequestParameters;
    @XmlElement(name = "CustomParameters")
    protected CustomParameters customParameters;

    /**
     * Gets the value of the genericRequestParameters property.
     * 
     * @return
     *     possible object is
     *     {@link GenericRequestParameters }
     *     
     */
    public GenericRequestParameters getGenericRequestParameters() {
        return genericRequestParameters;
    }

    /**
     * Sets the value of the genericRequestParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericRequestParameters }
     *     
     */
    public void setGenericRequestParameters(GenericRequestParameters value) {
        this.genericRequestParameters = value;
    }

    /**
     * Gets the value of the customParameters property.
     * 
     * @return
     *     possible object is
     *     {@link CustomParameters }
     *     
     */
    public CustomParameters getCustomParameters() {
        return customParameters;
    }

    /**
     * Sets the value of the customParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomParameters }
     *     
     */
    public void setCustomParameters(CustomParameters value) {
        this.customParameters = value;
    }

}
