//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.30 at 12:06:50 PM COT 
//


package ar.com.macro.validacion.model.client.daonengine.dto.soap;

import javax.xml.bind.annotation.*;


/**
 * Base type for list Requests.
 * 
 * <p>Java class for AbstractListRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractListRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.daon.com/ws/de}AbstractRequest"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ReturnSetCriteria" type="{http://www.daon.com/ws/de}ReturnSetCriteria" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractListRequest", propOrder = {
    "returnSetCriteria"
})
@XmlSeeAlso({
    AbstractOrderedListRequest.class
})
public abstract class AbstractListRequest
    extends AbstractRequest
{

    @XmlElement(name = "ReturnSetCriteria")
    protected ReturnSetCriteria returnSetCriteria;

    /**
     * Gets the value of the returnSetCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnSetCriteria }
     *     
     */
    public ReturnSetCriteria getReturnSetCriteria() {
        return returnSetCriteria;
    }

    /**
     * Sets the value of the returnSetCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnSetCriteria }
     *     
     */
    public void setReturnSetCriteria(ReturnSetCriteria value) {
        this.returnSetCriteria = value;
    }

}
