//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.30 at 12:06:50 PM COT 
//


package ar.com.macro.validacion.model.client.daonengine.dto.soap;

import javax.xml.bind.annotation.*;


/**
 * Base type for Responses.
 * 
 * <p>Java class for AbstractDaonEngineResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractDaonEngineResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.daon.com/ws/de}AbstractResponse"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RequestTrackingUID" type="{http://www.daon.com/ws/de}RequestTrackingUID" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractDaonEngineResponse", propOrder = {
    "requestTrackingUID"
})
@XmlSeeAlso({
    UpdateIdentityResponse.class,
    UpdateIdentitiesResponse.class,
    ListIdentitiesResponse.class,
    GetIdentityResponse.class,
    GetIdentityDescriptionResponse.class,
    GetIdentityCountResponse.class,
    GetIdentitiesResponse.class,
    DeleteIdentityResponse.class,
    DeleteIdentitiesResponse.class,
    CreateIdentityResponse.class,
    CreateIdentitiesResponse.class
})
public abstract class AbstractDaonEngineResponse
    extends AbstractResponse
{

    @XmlElement(name = "RequestTrackingUID")
    protected String requestTrackingUID;

    /**
     * Gets the value of the requestTrackingUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestTrackingUID() {
        return requestTrackingUID;
    }

    /**
     * Sets the value of the requestTrackingUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestTrackingUID(String value) {
        this.requestTrackingUID = value;
    }

}
