//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.30 at 12:06:50 PM COT 
//


package ar.com.macro.validacion.model.client.daonengine.dto.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * Information on an Identity's biographic data.
 * 					
 * 
 * <p>Java class for BiographicDataInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BiographicDataInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="StringItemInfo" type="{http://www.daon.com/ws/de}StringItemInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="LongItemInfo" type="{http://www.daon.com/ws/de}LongItemInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="DoubleItemInfo" type="{http://www.daon.com/ws/de}DoubleItemInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="DateItemInfo" type="{http://www.daon.com/ws/de}DateItemInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="TimestampItemInfo" type="{http://www.daon.com/ws/de}TimestampItemInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ExtendedStringItemInfo" type="{http://www.daon.com/ws/de}ExtendedStringItemInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ExtendedBinaryItemInfo" type="{http://www.daon.com/ws/de}ExtendedBinaryItemInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BiographicDataInfo", propOrder = {
    "stringItemInfo",
    "longItemInfo",
    "doubleItemInfo",
    "dateItemInfo",
    "timestampItemInfo",
    "extendedStringItemInfo",
    "extendedBinaryItemInfo"
})
public class BiographicDataInfo {

    @XmlElement(name = "StringItemInfo")
    protected List<StringItemInfo> stringItemInfo;
    @XmlElement(name = "LongItemInfo")
    protected List<LongItemInfo> longItemInfo;
    @XmlElement(name = "DoubleItemInfo")
    protected List<DoubleItemInfo> doubleItemInfo;
    @XmlElement(name = "DateItemInfo")
    protected List<DateItemInfo> dateItemInfo;
    @XmlElement(name = "TimestampItemInfo")
    protected List<TimestampItemInfo> timestampItemInfo;
    @XmlElement(name = "ExtendedStringItemInfo")
    protected List<ExtendedStringItemInfo> extendedStringItemInfo;
    @XmlElement(name = "ExtendedBinaryItemInfo")
    protected List<ExtendedBinaryItemInfo> extendedBinaryItemInfo;

    /**
     * Gets the value of the stringItemInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stringItemInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStringItemInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StringItemInfo }
     * 
     * 
     */
    public List<StringItemInfo> getStringItemInfo() {
        if (stringItemInfo == null) {
            stringItemInfo = new ArrayList<StringItemInfo>();
        }
        return this.stringItemInfo;
    }

    /**
     * Gets the value of the longItemInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the longItemInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLongItemInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LongItemInfo }
     * 
     * 
     */
    public List<LongItemInfo> getLongItemInfo() {
        if (longItemInfo == null) {
            longItemInfo = new ArrayList<LongItemInfo>();
        }
        return this.longItemInfo;
    }

    /**
     * Gets the value of the doubleItemInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the doubleItemInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDoubleItemInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DoubleItemInfo }
     * 
     * 
     */
    public List<DoubleItemInfo> getDoubleItemInfo() {
        if (doubleItemInfo == null) {
            doubleItemInfo = new ArrayList<DoubleItemInfo>();
        }
        return this.doubleItemInfo;
    }

    /**
     * Gets the value of the dateItemInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dateItemInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDateItemInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateItemInfo }
     * 
     * 
     */
    public List<DateItemInfo> getDateItemInfo() {
        if (dateItemInfo == null) {
            dateItemInfo = new ArrayList<DateItemInfo>();
        }
        return this.dateItemInfo;
    }

    /**
     * Gets the value of the timestampItemInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timestampItemInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTimestampItemInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimestampItemInfo }
     * 
     * 
     */
    public List<TimestampItemInfo> getTimestampItemInfo() {
        if (timestampItemInfo == null) {
            timestampItemInfo = new ArrayList<TimestampItemInfo>();
        }
        return this.timestampItemInfo;
    }

    /**
     * Gets the value of the extendedStringItemInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extendedStringItemInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtendedStringItemInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtendedStringItemInfo }
     * 
     * 
     */
    public List<ExtendedStringItemInfo> getExtendedStringItemInfo() {
        if (extendedStringItemInfo == null) {
            extendedStringItemInfo = new ArrayList<ExtendedStringItemInfo>();
        }
        return this.extendedStringItemInfo;
    }

    /**
     * Gets the value of the extendedBinaryItemInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extendedBinaryItemInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtendedBinaryItemInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtendedBinaryItemInfo }
     * 
     * 
     */
    public List<ExtendedBinaryItemInfo> getExtendedBinaryItemInfo() {
        if (extendedBinaryItemInfo == null) {
            extendedBinaryItemInfo = new ArrayList<ExtendedBinaryItemInfo>();
        }
        return this.extendedBinaryItemInfo;
    }

}
