//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.30 at 12:06:50 PM COT 
//


package ar.com.macro.validacion.model.client.daonengine.dto.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Filter used to include/exclude biographic data.
 * 						This is
 * 						an abstract type - IncludeAllBiographicDataFilter,
 * 						InclusiveBiographicDataFilter or
 * 						ExclusiveBiographicDataFilter must be used when
 * 						specifying the filter.
 * 					
 * 
 * <p>Java class for BiographicDataFilter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BiographicDataFilter"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BiographicDataFilter")
@XmlSeeAlso({
    ExclusiveBiographicDataFilter.class,
    IncludeAllBiographicDataFilter.class,
    InclusiveBiographicDataFilter.class
})
public abstract class BiographicDataFilter {


}
