//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.30 at 12:06:50 PM COT 
//


package ar.com.macro.validacion.model.client.daonengine.dto.soap;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * Get one or more Identities and specific data
 * 							associated with the given Identities. <p>
 * 
 * 							An IdentityDataFilter can be used to indicate the
 * 							biographic and biometric data to be returned <p>
 * 
 * 							If the IdentityDataFilter is not specified then only
 * 							core data associated with the given Identities will
 * 							be returned.
 * 
 * 							Note that duplicate Identities will not be returned.
 * 						
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.daon.com/ws/de}AbstractRequest"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DomainIdentifier" type="{http://www.daon.com/ws/de}DomainIdentifier"/&gt;
 *         &lt;element name="IdentityIdentifier" type="{http://www.daon.com/ws/de}IdentityIdentifier" maxOccurs="unbounded"/&gt;
 *         &lt;element name="IdentityDataFilter" type="{http://www.daon.com/ws/de}IdentityDataFilter" minOccurs="0"/&gt;
 *         &lt;element name="TransformPolicyIdentifier" type="{http://www.daon.com/ws/de}PolicyIdentifier" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "domainIdentifier",
    "identityIdentifier",
    "identityDataFilter",
    "transformPolicyIdentifier"
})
@XmlRootElement(name = "GetIdentitiesRequest")
public class GetIdentitiesRequest
    extends AbstractRequest
{

    @XmlElement(name = "DomainIdentifier", required = true)
    protected DomainIdentifier domainIdentifier;
    @XmlElement(name = "IdentityIdentifier", required = true)
    protected List<IdentityIdentifier> identityIdentifier;
    @XmlElement(name = "IdentityDataFilter")
    protected IdentityDataFilter identityDataFilter;
    @XmlElement(name = "TransformPolicyIdentifier")
    protected PolicyIdentifier transformPolicyIdentifier;

    /**
     * Gets the value of the domainIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link DomainIdentifier }
     *     
     */
    public DomainIdentifier getDomainIdentifier() {
        return domainIdentifier;
    }

    /**
     * Sets the value of the domainIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainIdentifier }
     *     
     */
    public void setDomainIdentifier(DomainIdentifier value) {
        this.domainIdentifier = value;
    }

    /**
     * Gets the value of the identityIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identityIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentityIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentityIdentifier }
     * 
     * 
     */
    public List<IdentityIdentifier> getIdentityIdentifier() {
        if (identityIdentifier == null) {
            identityIdentifier = new ArrayList<IdentityIdentifier>();
        }
        return this.identityIdentifier;
    }

    /**
     * Gets the value of the identityDataFilter property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityDataFilter }
     *     
     */
    public IdentityDataFilter getIdentityDataFilter() {
        return identityDataFilter;
    }

    /**
     * Sets the value of the identityDataFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityDataFilter }
     *     
     */
    public void setIdentityDataFilter(IdentityDataFilter value) {
        this.identityDataFilter = value;
    }

    /**
     * Gets the value of the transformPolicyIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyIdentifier }
     *     
     */
    public PolicyIdentifier getTransformPolicyIdentifier() {
        return transformPolicyIdentifier;
    }

    /**
     * Sets the value of the transformPolicyIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyIdentifier }
     *     
     */
    public void setTransformPolicyIdentifier(PolicyIdentifier value) {
        this.transformPolicyIdentifier = value;
    }

}
