//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.30 at 12:06:50 PM COT 
//


package ar.com.macro.validacion.model.client.daonengine.dto.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A Policy
 * 
 * <p>Java class for Policy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Policy"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.daon.com/ws/de}PolicyDescription"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PolicyDocument" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Policy", propOrder = {
    "policyDocument"
})
public class Policy
    extends PolicyDescription
{

    @XmlElement(name = "PolicyDocument", required = true)
    protected byte[] policyDocument;

    /**
     * Gets the value of the policyDocument property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getPolicyDocument() {
        return policyDocument;
    }

    /**
     * Sets the value of the policyDocument property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setPolicyDocument(byte[] value) {
        this.policyDocument = value;
    }

}
