//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.30 at 12:06:50 PM COT 
//


package ar.com.macro.validacion.model.client.daonengine.dto.soap;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SymmetricKeyType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SymmetricKeyType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="TRIPLE_DES_192"/&gt;
 *     &lt;enumeration value="AES_128"/&gt;
 *     &lt;enumeration value="AES_192"/&gt;
 *     &lt;enumeration value="AES_256"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SymmetricKeyType")
@XmlEnum
public enum SymmetricKeyType {

    TRIPLE_DES_192,
    AES_128,
    AES_192,
    AES_256;

    public String value() {
        return name();
    }

    public static SymmetricKeyType fromValue(String v) {
        return valueOf(v);
    }

}
