apiVersion: v1
kind: Service
metadata:
  name: db-etl-service
  namespace: biometria-ns
spec:
  type: ExternalName
  externalName: rds-biometria-prod-mighuellas.cquragsgcfvk.us-east-1.rds.amazonaws.com
  selector: {} 