package ar.com.macro.constant;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum Validacion3DFL {

	VALIDACION_VIDEO_RESULTADO_FACE_OK("MATCH"),
	VALIDACION_VIDEO_RESULTADO_LIVENESS_OK("PASS"),
	VALIDACION_VIDEO_RESULTADO_FACE_AUTHENTICATION("FA"),
	VALIDACION_VIDEO_RESULTADO_LIVENESS_ASSESMENT("LA"),
	VALIDACION_VIDEO_STATUS_PROCESAMIENTO_FALLA("FAILED"),
	VALIDACION_VIDEO_STATUS_PROCESAMIENTO_PROCESSED("PROCESSED"),
	VALIDACION_VIDEO_STATUS_MATCH_PASS("1"),
	VALIDACION_VIDEO_STATUS_MATCH_NO_PASS("2"),
	VALIDACION_VIDEO_STATUS_NO_MATCH_PASS("3"),
	VALIDACION_VIDEO_STATUS_NO_MATCH_NO_PASS("4");
	
	String value;
}
