server:
  port: ${macro.spring.port}

  ssl:
    enabled: true
    key-store: ${macro.home.security.cert.path}
    key-store-password: ${macro.home.security.cert.password}
    keyStoreType: PKCS12
    #keyAlias: localhost
    clientAuth: want

springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:false}
    disable-swagger-default-url: true

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
# Actuator
management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      base-path: /${macro.spring.serviceid}/manager
      exposure:
        include: "*"
      cors:
        allowed-origins: true


info:
  app:
    microservicio: ${macro.microservicio.nombre}
    version: "@project.version@"
    artefacto: ${macro.microservicio.artefacto}
    group: "@project.groupId@"
    lastBuildDate: "@timestamp@"
    jenkins-build: "@jenkins.build.number@"
  java:
    version: "@java.version@"
  config:
    env: ${api.macro.entorno.valor}
    serviceid: ${macro.spring.serviceid}
    port: ${macro.spring.port}
    eureka-host: ${macro.eureka.instance.hostname}
    discovery-server: ${macro.instance.discovery.host}:${macro.instance.discovery.port}
    key-store: ${macro.home.security.cert.path}

---
spring:
  config:
    activate:
      on-profile: eureka
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  application:
    name: ${macro.spring.serviceid}


eureka:
  instance:
    secureVirtualHostName: ${spring.application.name}
    securePort: ${server.port}
    hostname: ${macro.eureka.instance.hostname}
    instanceId: ${spring.application.name}:${server.port}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    preferIpAddress: false
    nonSecurePortEnabled: false
    securePortEnabled:  true
    leaseRenewalIntervalInSeconds: 30
    lease-expiration-duration-in-seconds: 30
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}${management.endpoints.web.base-path}/info
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/swagger-ui.html

  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 30
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: https://${macro.instance.discovery.host}:${macro.instance.discovery.port}/eureka/

# habilitacion de ribbon para el balanceo, no cambiar
ribbon:
  eureka:
    enabled: true

# Logging
logging:
  config: ${macro.home.config}/logback-spring.xml

feign:
  client:
    config:
      default:
        connectTimeout: 100000
        readTimeout: 100000

---

spring:
  config:
    activate:
      on-profile: kubernetes
  autoconfigure:
    exclude:
      - org.springframework.cloud.client.serviceregistry.ServiceRegistryAutoConfiguration
      - org.springframework.cloud.client.serviceregistry.AutoServiceRegistrationAutoConfiguration

  application:
    name: macro-bio-datosgenerales
    loadbalancer:
      enabled: true
      ribbon:
        enabled: false
    kubernetes:
      loadbalancer:
        enabled: true
      discovery:
        all-namespaces: true
      reload:
        period: 1000
        enabled: true
      config:
        name: macro-bio-datosgenerales
        sources:
          - name: ${CONFIGMAP_VERSION}
