//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.14 at 09:18:33 PM ART 
//


package ar.com.macro.validacion.model.client.daonengine.identification.dto.soap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Return a Search Data for a specified Transaction Identifier.
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.daon.com/ws/de}AbstractDaonEngineResponse"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ResponseData" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="SearchData"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="GenericRequestParameters" type="{http://www.daon.com/ws/de}GenericRequestParameters"/&gt;
 *                             &lt;element name="CustomParameters" type="{http://www.daon.com/ws/de}CustomParameters" minOccurs="0"/&gt;
 *                             &lt;element name="DomainIdentifier" type="{http://www.daon.com/ws/de}DomainIdentifier"/&gt;
 *                             &lt;element name="SearchPolicyIdentifier" type="{http://www.daon.com/ws/de}PolicyIdentifier"/&gt;
 *                             &lt;element name="TransactionIdentifier" type="{http://www.daon.com/ws/de}TransactionIdentifier"/&gt;
 *                             &lt;element name="ResultNotificationAddress" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/&gt;
 *                             &lt;element name="GroupIdentifier" type="{http://www.daon.com/ws/de}GroupIdentifier" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                             &lt;element name="Identity" type="{http://www.daon.com/ws/de}Identity"/&gt;
 *                             &lt;element name="SearchParameters" type="{http://www.daon.com/ws/de}SearchParameters" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "responseData"
})
@XmlRootElement(name = "GetAsyncSearchDataResponse")
public class GetAsyncSearchDataResponse
    extends AbstractDaonEngineResponse
{

    @XmlElement(name = "ResponseData")
    protected GetAsyncSearchDataResponse.ResponseData responseData;

    /**
     * Gets the value of the responseData property.
     * 
     * @return
     *     possible object is
     *     {@link GetAsyncSearchDataResponse.ResponseData }
     *     
     */
    public GetAsyncSearchDataResponse.ResponseData getResponseData() {
        return responseData;
    }

    /**
     * Sets the value of the responseData property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetAsyncSearchDataResponse.ResponseData }
     *     
     */
    public void setResponseData(GetAsyncSearchDataResponse.ResponseData value) {
        this.responseData = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="SearchData"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="GenericRequestParameters" type="{http://www.daon.com/ws/de}GenericRequestParameters"/&gt;
     *                   &lt;element name="CustomParameters" type="{http://www.daon.com/ws/de}CustomParameters" minOccurs="0"/&gt;
     *                   &lt;element name="DomainIdentifier" type="{http://www.daon.com/ws/de}DomainIdentifier"/&gt;
     *                   &lt;element name="SearchPolicyIdentifier" type="{http://www.daon.com/ws/de}PolicyIdentifier"/&gt;
     *                   &lt;element name="TransactionIdentifier" type="{http://www.daon.com/ws/de}TransactionIdentifier"/&gt;
     *                   &lt;element name="ResultNotificationAddress" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/&gt;
     *                   &lt;element name="GroupIdentifier" type="{http://www.daon.com/ws/de}GroupIdentifier" maxOccurs="unbounded" minOccurs="0"/&gt;
     *                   &lt;element name="Identity" type="{http://www.daon.com/ws/de}Identity"/&gt;
     *                   &lt;element name="SearchParameters" type="{http://www.daon.com/ws/de}SearchParameters" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "searchData"
    })
    public static class ResponseData {

        @XmlElement(name = "SearchData", required = true)
        protected GetAsyncSearchDataResponse.ResponseData.SearchData searchData;

        /**
         * Gets the value of the searchData property.
         * 
         * @return
         *     possible object is
         *     {@link GetAsyncSearchDataResponse.ResponseData.SearchData }
         *     
         */
        public GetAsyncSearchDataResponse.ResponseData.SearchData getSearchData() {
            return searchData;
        }

        /**
         * Sets the value of the searchData property.
         * 
         * @param value
         *     allowed object is
         *     {@link GetAsyncSearchDataResponse.ResponseData.SearchData }
         *     
         */
        public void setSearchData(GetAsyncSearchDataResponse.ResponseData.SearchData value) {
            this.searchData = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="GenericRequestParameters" type="{http://www.daon.com/ws/de}GenericRequestParameters"/&gt;
         *         &lt;element name="CustomParameters" type="{http://www.daon.com/ws/de}CustomParameters" minOccurs="0"/&gt;
         *         &lt;element name="DomainIdentifier" type="{http://www.daon.com/ws/de}DomainIdentifier"/&gt;
         *         &lt;element name="SearchPolicyIdentifier" type="{http://www.daon.com/ws/de}PolicyIdentifier"/&gt;
         *         &lt;element name="TransactionIdentifier" type="{http://www.daon.com/ws/de}TransactionIdentifier"/&gt;
         *         &lt;element name="ResultNotificationAddress" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/&gt;
         *         &lt;element name="GroupIdentifier" type="{http://www.daon.com/ws/de}GroupIdentifier" maxOccurs="unbounded" minOccurs="0"/&gt;
         *         &lt;element name="Identity" type="{http://www.daon.com/ws/de}Identity"/&gt;
         *         &lt;element name="SearchParameters" type="{http://www.daon.com/ws/de}SearchParameters" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "genericRequestParameters",
            "customParameters",
            "domainIdentifier",
            "searchPolicyIdentifier",
            "transactionIdentifier",
            "resultNotificationAddress",
            "groupIdentifier",
            "identity",
            "searchParameters"
        })
        public static class SearchData {

            @XmlElement(name = "GenericRequestParameters", required = true)
            protected GenericRequestParameters genericRequestParameters;
            @XmlElement(name = "CustomParameters")
            protected CustomParameters customParameters;
            @XmlElement(name = "DomainIdentifier", required = true)
            protected DomainIdentifier domainIdentifier;
            @XmlElement(name = "SearchPolicyIdentifier", required = true)
            protected PolicyIdentifier searchPolicyIdentifier;
            @XmlElement(name = "TransactionIdentifier", required = true)
            protected String transactionIdentifier;
            @XmlElement(name = "ResultNotificationAddress")
            @XmlSchemaType(name = "anyURI")
            protected String resultNotificationAddress;
            @XmlElement(name = "GroupIdentifier")
            protected List<GroupIdentifier> groupIdentifier;
            @XmlElement(name = "Identity", required = true)
            protected Identity identity;
            @XmlElement(name = "SearchParameters")
            protected SearchParameters searchParameters;

            /**
             * Gets the value of the genericRequestParameters property.
             * 
             * @return
             *     possible object is
             *     {@link GenericRequestParameters }
             *     
             */
            public GenericRequestParameters getGenericRequestParameters() {
                return genericRequestParameters;
            }

            /**
             * Sets the value of the genericRequestParameters property.
             * 
             * @param value
             *     allowed object is
             *     {@link GenericRequestParameters }
             *     
             */
            public void setGenericRequestParameters(GenericRequestParameters value) {
                this.genericRequestParameters = value;
            }

            /**
             * Gets the value of the customParameters property.
             * 
             * @return
             *     possible object is
             *     {@link CustomParameters }
             *     
             */
            public CustomParameters getCustomParameters() {
                return customParameters;
            }

            /**
             * Sets the value of the customParameters property.
             * 
             * @param value
             *     allowed object is
             *     {@link CustomParameters }
             *     
             */
            public void setCustomParameters(CustomParameters value) {
                this.customParameters = value;
            }

            /**
             * Gets the value of the domainIdentifier property.
             * 
             * @return
             *     possible object is
             *     {@link DomainIdentifier }
             *     
             */
            public DomainIdentifier getDomainIdentifier() {
                return domainIdentifier;
            }

            /**
             * Sets the value of the domainIdentifier property.
             * 
             * @param value
             *     allowed object is
             *     {@link DomainIdentifier }
             *     
             */
            public void setDomainIdentifier(DomainIdentifier value) {
                this.domainIdentifier = value;
            }

            /**
             * Gets the value of the searchPolicyIdentifier property.
             * 
             * @return
             *     possible object is
             *     {@link PolicyIdentifier }
             *     
             */
            public PolicyIdentifier getSearchPolicyIdentifier() {
                return searchPolicyIdentifier;
            }

            /**
             * Sets the value of the searchPolicyIdentifier property.
             * 
             * @param value
             *     allowed object is
             *     {@link PolicyIdentifier }
             *     
             */
            public void setSearchPolicyIdentifier(PolicyIdentifier value) {
                this.searchPolicyIdentifier = value;
            }

            /**
             * Gets the value of the transactionIdentifier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTransactionIdentifier() {
                return transactionIdentifier;
            }

            /**
             * Sets the value of the transactionIdentifier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTransactionIdentifier(String value) {
                this.transactionIdentifier = value;
            }

            /**
             * Gets the value of the resultNotificationAddress property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getResultNotificationAddress() {
                return resultNotificationAddress;
            }

            /**
             * Sets the value of the resultNotificationAddress property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setResultNotificationAddress(String value) {
                this.resultNotificationAddress = value;
            }

            /**
             * Gets the value of the groupIdentifier property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the groupIdentifier property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getGroupIdentifier().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link GroupIdentifier }
             * 
             * 
             */
            public List<GroupIdentifier> getGroupIdentifier() {
                if (groupIdentifier == null) {
                    groupIdentifier = new ArrayList<GroupIdentifier>();
                }
                return this.groupIdentifier;
            }

            /**
             * Gets the value of the identity property.
             * 
             * @return
             *     possible object is
             *     {@link Identity }
             *     
             */
            public Identity getIdentity() {
                return identity;
            }

            /**
             * Sets the value of the identity property.
             * 
             * @param value
             *     allowed object is
             *     {@link Identity }
             *     
             */
            public void setIdentity(Identity value) {
                this.identity = value;
            }

            /**
             * Gets the value of the searchParameters property.
             * 
             * @return
             *     possible object is
             *     {@link SearchParameters }
             *     
             */
            public SearchParameters getSearchParameters() {
                return searchParameters;
            }

            /**
             * Sets the value of the searchParameters property.
             * 
             * @param value
             *     allowed object is
             *     {@link SearchParameters }
             *     
             */
            public void setSearchParameters(SearchParameters value) {
                this.searchParameters = value;
            }

        }

    }

}
