//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.14 at 09:18:33 PM ART 
//


package ar.com.macro.validacion.model.client.daonengine.identification.dto.soap;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.daon.ws.de package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AbstractScore_QNAME = new QName("http://www.daon.com/ws/de", "AbstractScore");
    private final static QName _AsyncSearchRequest_QNAME = new QName("http://www.daon.com/ws/de", "AsyncSearchRequest");
    private final static QName _FMR_QNAME = new QName("http://www.daon.com/ws/de", "FMR");
    private final static QName _RawScore_QNAME = new QName("http://www.daon.com/ws/de", "RawScore");
    private final static QName _SearchRequest_QNAME = new QName("http://www.daon.com/ws/de", "SearchRequest");
    private final static QName _SearchResponse_QNAME = new QName("http://www.daon.com/ws/de", "SearchResponse");
    
    private final static QName _Binary_QNAME = new QName("http://www.daon.com/de/metadata", "Binary");
    private final static QName _NameValuePair_QNAME = new QName("http://www.daon.com/de/metadata", "NameValuePair");
    private final static QName _Boolean_QNAME = new QName("http://www.daon.com/de/metadata", "Boolean");
    private final static QName _DataTime_QNAME = new QName("http://www.daon.com/de/metadata", "DataTime");
    private final static QName _Date_QNAME = new QName("http://www.daon.com/de/metadata", "Date");
    private final static QName _Double_QNAME = new QName("http://www.daon.com/de/metadata", "Double");
    private final static QName _Integer_QNAME = new QName("http://www.daon.com/de/metadata", "Integer");
    private final static QName _MetaData_QNAME = new QName("http://www.daon.com/de/metadata", "MetaData");
    private final static QName _MetaDataItem_QNAME = new QName("http://www.daon.com/de/metadata", "MetaDataItem");
    private final static QName _Nested_QNAME = new QName("http://www.daon.com/de/metadata", "Nested");
    private final static QName _OptionalNestedNameValuePair_QNAME = new QName("http://www.daon.com/de/metadata", "OptionalNestedNameValuePair");
    private final static QName _String_QNAME = new QName("http://www.daon.com/de/metadata", "String");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.daon.ws.de
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AsyncCreateAndSearchResponse }
     * 
     */
    public AsyncCreateAndSearchResponse createAsyncCreateAndSearchResponse() {
        return new AsyncCreateAndSearchResponse();
    }

    /**
     * Create an instance of {@link GetAsyncSearchDataResponse }
     * 
     */
    public GetAsyncSearchDataResponse createGetAsyncSearchDataResponse() {
        return new GetAsyncSearchDataResponse();
    }

    /**
     * Create an instance of {@link GetAsyncSearchResultsResponse }
     * 
     */
    public GetAsyncSearchResultsResponse createGetAsyncSearchResultsResponse() {
        return new GetAsyncSearchResultsResponse();
    }

    /**
     * Create an instance of {@link TransformResponse }
     * 
     */
    public TransformResponse createTransformResponse() {
        return new TransformResponse();
    }

    /**
     * Create an instance of {@link VerifiesResponse }
     * 
     */
    public VerifiesResponse createVerifiesResponse() {
        return new VerifiesResponse();
    }

    /**
     * Create an instance of {@link VerifyResponse }
     * 
     */
    public VerifyResponse createVerifyResponse() {
        return new VerifyResponse();
    }

    /**
     * Create an instance of {@link Candidate }
     * 
     */
    public Candidate createCandidate() {
        return new Candidate();
    }

    /**
     * Create an instance of {@link BiometricDataElement }
     * 
     */
    public BiometricDataElement createBiometricDataElement() {
        return new BiometricDataElement();
    }

    /**
     * Create an instance of {@link VerifyResponse.ResponseData }
     * 
     */
    public VerifyResponse.ResponseData createVerifyResponseResponseData() {
        return new VerifyResponse.ResponseData();
    }

    /**
     * Create an instance of {@link VerifiesResponse.ResponseData }
     * 
     */
    public VerifiesResponse.ResponseData createVerifiesResponseResponseData() {
        return new VerifiesResponse.ResponseData();
    }

    /**
     * Create an instance of {@link VerifiesResponse.ResponseData.CandidateResults }
     * 
     */
    public VerifiesResponse.ResponseData.CandidateResults createVerifiesResponseResponseDataCandidateResults() {
        return new VerifiesResponse.ResponseData.CandidateResults();
    }

    /**
     * Create an instance of {@link VerifiesResponse.ResponseData.CandidateResults.CandidateResult }
     * 
     */
    public VerifiesResponse.ResponseData.CandidateResults.CandidateResult createVerifiesResponseResponseDataCandidateResultsCandidateResult() {
        return new VerifiesResponse.ResponseData.CandidateResults.CandidateResult();
    }

    /**
     * Create an instance of {@link VerifyParameters }
     * 
     */
    public VerifyParameters createVerifyParameters() {
        return new VerifyParameters();
    }

    /**
     * Create an instance of {@link SearchResponse }
     * 
     */
    public SearchResponse createSearchResponse() {
        return new SearchResponse();
    }

    /**
     * Create an instance of {@link GetAsyncSearchDataResponse.ResponseData }
     * 
     */
    public GetAsyncSearchDataResponse.ResponseData createGetAsyncSearchDataResponseResponseData() {
        return new GetAsyncSearchDataResponse.ResponseData();
    }

    /**
     * Create an instance of {@link SearchParameters }
     * 
     */
    public SearchParameters createSearchParameters() {
        return new SearchParameters();
    }

    /**
     * Create an instance of {@link VerificationAdjudication }
     * 
     */
    public VerificationAdjudication createVerificationAdjudication() {
        return new VerificationAdjudication();
    }

    /**
     * Create an instance of {@link SearchAdjudication }
     * 
     */
    public SearchAdjudication createSearchAdjudication() {
        return new SearchAdjudication();
    }

    /**
     * Create an instance of {@link AdjudicateSearchRequest }
     * 
     */
    public AdjudicateSearchRequest createAdjudicateSearchRequest() {
        return new AdjudicateSearchRequest();
    }

    /**
     * Create an instance of {@link GenericRequestParameters }
     * 
     */
    public GenericRequestParameters createGenericRequestParameters() {
        return new GenericRequestParameters();
    }

    /**
     * Create an instance of {@link CustomParameters }
     * 
     */
    public CustomParameters createCustomParameters() {
        return new CustomParameters();
    }

    /**
     * Create an instance of {@link DomainIdentifier }
     * 
     */
    public DomainIdentifier createDomainIdentifier() {
        return new DomainIdentifier();
    }

    /**
     * Create an instance of {@link AdjudicateSearchResponse }
     * 
     */
    public AdjudicateSearchResponse createAdjudicateSearchResponse() {
        return new AdjudicateSearchResponse();
    }

    /**
     * Create an instance of {@link ResponseStatus }
     * 
     */
    public ResponseStatus createResponseStatus() {
        return new ResponseStatus();
    }

    /**
     * Create an instance of {@link AdjudicateVerificationRequest }
     * 
     */
    public AdjudicateVerificationRequest createAdjudicateVerificationRequest() {
        return new AdjudicateVerificationRequest();
    }

    /**
     * Create an instance of {@link AdjudicateVerificationResponse }
     * 
     */
    public AdjudicateVerificationResponse createAdjudicateVerificationResponse() {
        return new AdjudicateVerificationResponse();
    }

    /**
     * Create an instance of {@link AsyncCreateAndSearchRequest }
     * 
     */
    public AsyncCreateAndSearchRequest createAsyncCreateAndSearchRequest() {
        return new AsyncCreateAndSearchRequest();
    }

    /**
     * Create an instance of {@link AsyncSearchRequest }
     * 
     */
    public AsyncSearchRequest createAsyncSearchRequest() {
        return new AsyncSearchRequest();
    }

    /**
     * Create an instance of {@link PolicyIdentifier }
     * 
     */
    public PolicyIdentifier createPolicyIdentifier() {
        return new PolicyIdentifier();
    }

    /**
     * Create an instance of {@link GroupIdentifier }
     * 
     */
    public GroupIdentifier createGroupIdentifier() {
        return new GroupIdentifier();
    }

    /**
     * Create an instance of {@link Identity }
     * 
     */
    public Identity createIdentity() {
        return new Identity();
    }

    /**
     * Create an instance of {@link AsyncCreateAndSearchResponse.ResponseData }
     * 
     */
    public AsyncCreateAndSearchResponse.ResponseData createAsyncCreateAndSearchResponseResponseData() {
        return new AsyncCreateAndSearchResponse.ResponseData();
    }

    /**
     * Create an instance of {@link AsyncSearchResponse }
     * 
     */
    public AsyncSearchResponse createAsyncSearchResponse() {
        return new AsyncSearchResponse();
    }

    /**
     * Create an instance of {@link FMR }
     * 
     */
    public FMR createFMR() {
        return new FMR();
    }

    /**
     * Create an instance of {@link GetAsyncSearchDataRequest }
     * 
     */
    public GetAsyncSearchDataRequest createGetAsyncSearchDataRequest() {
        return new GetAsyncSearchDataRequest();
    }

    /**
     * Create an instance of {@link GetAsyncSearchResultsRequest }
     * 
     */
    public GetAsyncSearchResultsRequest createGetAsyncSearchResultsRequest() {
        return new GetAsyncSearchResultsRequest();
    }

    /**
     * Create an instance of {@link GetAsyncSearchResultsResponse.ResponseData }
     * 
     */
    public GetAsyncSearchResultsResponse.ResponseData createGetAsyncSearchResultsResponseResponseData() {
        return new GetAsyncSearchResultsResponse.ResponseData();
    }

    /**
     * Create an instance of {@link GetSearchAdjudicationRequest }
     * 
     */
    public GetSearchAdjudicationRequest createGetSearchAdjudicationRequest() {
        return new GetSearchAdjudicationRequest();
    }

    /**
     * Create an instance of {@link IdentityIdentifier }
     * 
     */
    public IdentityIdentifier createIdentityIdentifier() {
        return new IdentityIdentifier();
    }

    /**
     * Create an instance of {@link GetSearchAdjudicationResponse }
     * 
     */
    public GetSearchAdjudicationResponse createGetSearchAdjudicationResponse() {
        return new GetSearchAdjudicationResponse();
    }

    /**
     * Create an instance of {@link GetVerificationAdjudicationRequest }
     * 
     */
    public GetVerificationAdjudicationRequest createGetVerificationAdjudicationRequest() {
        return new GetVerificationAdjudicationRequest();
    }

    /**
     * Create an instance of {@link GetVerificationAdjudicationResponse }
     * 
     */
    public GetVerificationAdjudicationResponse createGetVerificationAdjudicationResponse() {
        return new GetVerificationAdjudicationResponse();
    }

    /**
     * Create an instance of {@link RawScore }
     * 
     */
    public RawScore createRawScore() {
        return new RawScore();
    }

    /**
     * Create an instance of {@link SearchRequest }
     * 
     */
    public SearchRequest createSearchRequest() {
        return new SearchRequest();
    }

    /**
     * Create an instance of {@link TransformRequest }
     * 
     */
    public TransformRequest createTransformRequest() {
        return new TransformRequest();
    }

    /**
     * Create an instance of {@link TransformResponse.ResponseData }
     * 
     */
    public TransformResponse.ResponseData createTransformResponseResponseData() {
        return new TransformResponse.ResponseData();
    }

    /**
     * Create an instance of {@link VerifiesRequest }
     * 
     */
    public VerifiesRequest createVerifiesRequest() {
        return new VerifiesRequest();
    }

    /**
     * Create an instance of {@link VerifyRequest }
     * 
     */
    public VerifyRequest createVerifyRequest() {
        return new VerifyRequest();
    }

    /**
     * Create an instance of {@link AsyncSearchResult }
     * 
     */
    public AsyncSearchResult createAsyncSearchResult() {
        return new AsyncSearchResult();
    }

    /**
     * Create an instance of {@link AsyncTransactionInfo }
     * 
     */
    public AsyncTransactionInfo createAsyncTransactionInfo() {
        return new AsyncTransactionInfo();
    }

    /**
     * Create an instance of {@link BiographicData }
     * 
     */
    public BiographicData createBiographicData() {
        return new BiographicData();
    }

    /**
     * Create an instance of {@link CoreData }
     * 
     */
    public CoreData createCoreData() {
        return new CoreData();
    }

    /**
     * Create an instance of {@link DateItem }
     * 
     */
    public DateItem createDateItem() {
        return new DateItem();
    }

    /**
     * Create an instance of {@link DoubleItem }
     * 
     */
    public DoubleItem createDoubleItem() {
        return new DoubleItem();
    }

    /**
     * Create an instance of {@link ExtendedBinaryItem }
     * 
     */
    public ExtendedBinaryItem createExtendedBinaryItem() {
        return new ExtendedBinaryItem();
    }

    /**
     * Create an instance of {@link ExtendedStringItem }
     * 
     */
    public ExtendedStringItem createExtendedStringItem() {
        return new ExtendedStringItem();
    }

    /**
     * Create an instance of {@link GroupMembership }
     * 
     */
    public GroupMembership createGroupMembership() {
        return new GroupMembership();
    }

    /**
     * Create an instance of {@link Key }
     * 
     */
    public Key createKey() {
        return new Key();
    }

    /**
     * Create an instance of {@link KeyIdentifier }
     * 
     */
    public KeyIdentifier createKeyIdentifier() {
        return new KeyIdentifier();
    }

    /**
     * Create an instance of {@link LongItem }
     * 
     */
    public LongItem createLongItem() {
        return new LongItem();
    }

    /**
     * Create an instance of {@link Other }
     * 
     */
    public Other createOther() {
        return new Other();
    }

    /**
     * Create an instance of {@link Policy }
     * 
     */
    public Policy createPolicy() {
        return new Policy();
    }

    /**
     * Create an instance of {@link PolicyDescription }
     * 
     */
    public PolicyDescription createPolicyDescription() {
        return new PolicyDescription();
    }

    /**
     * Create an instance of {@link PolicyDetails }
     * 
     */
    public PolicyDetails createPolicyDetails() {
        return new PolicyDetails();
    }

    /**
     * Create an instance of {@link ReturnSetCriteria }
     * 
     */
    public ReturnSetCriteria createReturnSetCriteria() {
        return new ReturnSetCriteria();
    }

    /**
     * Create an instance of {@link SampleScore }
     * 
     */
    public SampleScore createSampleScore() {
        return new SampleScore();
    }

    /**
     * Create an instance of {@link SearchAdjudicationDecision }
     * 
     */
    public SearchAdjudicationDecision createSearchAdjudicationDecision() {
        return new SearchAdjudicationDecision();
    }

    /**
     * Create an instance of {@link SearchRequestTrackingUID }
     * 
     */
    public SearchRequestTrackingUID createSearchRequestTrackingUID() {
        return new SearchRequestTrackingUID();
    }

    /**
     * Create an instance of {@link SearchTransactionIdentifier }
     * 
     */
    public SearchTransactionIdentifier createSearchTransactionIdentifier() {
        return new SearchTransactionIdentifier();
    }

    /**
     * Create an instance of {@link SecureEnvelope }
     * 
     */
    public SecureEnvelope createSecureEnvelope() {
        return new SecureEnvelope();
    }

    /**
     * Create an instance of {@link StringItem }
     * 
     */
    public StringItem createStringItem() {
        return new StringItem();
    }

    /**
     * Create an instance of {@link TimestampItem }
     * 
     */
    public TimestampItem createTimestampItem() {
        return new TimestampItem();
    }

    /**
     * Create an instance of {@link VerificationAdjudicationDecision }
     * 
     */
    public VerificationAdjudicationDecision createVerificationAdjudicationDecision() {
        return new VerificationAdjudicationDecision();
    }

    /**
     * Create an instance of {@link Candidate.CandidateScore }
     * 
     */
    public Candidate.CandidateScore createCandidateCandidateScore() {
        return new Candidate.CandidateScore();
    }

    /**
     * Create an instance of {@link BiometricDataElement.Data }
     * 
     */
    public BiometricDataElement.Data createBiometricDataElementData() {
        return new BiometricDataElement.Data();
    }

    /**
     * Create an instance of {@link VerifyResponse.ResponseData.VerifyScore }
     * 
     */
    public VerifyResponse.ResponseData.VerifyScore createVerifyResponseResponseDataVerifyScore() {
        return new VerifyResponse.ResponseData.VerifyScore();
    }

    /**
     * Create an instance of {@link VerifiesResponse.ResponseData.CandidateResults.CandidateMatchFailure }
     * 
     */
    public VerifiesResponse.ResponseData.CandidateResults.CandidateMatchFailure createVerifiesResponseResponseDataCandidateResultsCandidateMatchFailure() {
        return new VerifiesResponse.ResponseData.CandidateResults.CandidateMatchFailure();
    }

    /**
     * Create an instance of {@link VerifiesResponse.ResponseData.CandidateResults.CandidateResult.VerifyScore }
     * 
     */
    public VerifiesResponse.ResponseData.CandidateResults.CandidateResult.VerifyScore createVerifiesResponseResponseDataCandidateResultsCandidateResultVerifyScore() {
        return new VerifiesResponse.ResponseData.CandidateResults.CandidateResult.VerifyScore();
    }

    /**
     * Create an instance of {@link VerifyParameters.MatchThreshold }
     * 
     */
    public VerifyParameters.MatchThreshold createVerifyParametersMatchThreshold() {
        return new VerifyParameters.MatchThreshold();
    }

    /**
     * Create an instance of {@link SearchResponse.ResponseData }
     * 
     */
    public SearchResponse.ResponseData createSearchResponseResponseData() {
        return new SearchResponse.ResponseData();
    }

    /**
     * Create an instance of {@link GetAsyncSearchDataResponse.ResponseData.SearchData }
     * 
     */
    public GetAsyncSearchDataResponse.ResponseData.SearchData createGetAsyncSearchDataResponseResponseDataSearchData() {
        return new GetAsyncSearchDataResponse.ResponseData.SearchData();
    }

    /**
     * Create an instance of {@link SearchParameters.MatchThreshold }
     * 
     */
    public SearchParameters.MatchThreshold createSearchParametersMatchThreshold() {
        return new SearchParameters.MatchThreshold();
    }

    /**
     * Create an instance of {@link VerificationAdjudication.SampleDecision }
     * 
     */
    public VerificationAdjudication.SampleDecision createVerificationAdjudicationSampleDecision() {
        return new VerificationAdjudication.SampleDecision();
    }

    /**
     * Create an instance of {@link SearchAdjudication.SampleDecision }
     * 
     */
    public SearchAdjudication.SampleDecision createSearchAdjudicationSampleDecision() {
        return new SearchAdjudication.SampleDecision();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractScore }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractScore }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/ws/de", name = "AbstractScore")
    public JAXBElement<AbstractScore> createAbstractScore(AbstractScore value) {
        return new JAXBElement<AbstractScore>(_AbstractScore_QNAME, AbstractScore.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AsyncSearchRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AsyncSearchRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/ws/de", name = "AsyncSearchRequest")
    public JAXBElement<AsyncSearchRequest> createAsyncSearchRequest(AsyncSearchRequest value) {
        return new JAXBElement<AsyncSearchRequest>(_AsyncSearchRequest_QNAME, AsyncSearchRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FMR }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FMR }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/ws/de", name = "FMR")
    public JAXBElement<FMR> createFMR(FMR value) {
        return new JAXBElement<FMR>(_FMR_QNAME, FMR.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RawScore }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RawScore }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/ws/de", name = "RawScore")
    public JAXBElement<RawScore> createRawScore(RawScore value) {
        return new JAXBElement<RawScore>(_RawScore_QNAME, RawScore.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SearchRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/ws/de", name = "SearchRequest")
    public JAXBElement<SearchRequest> createSearchRequest(SearchRequest value) {
        return new JAXBElement<SearchRequest>(_SearchRequest_QNAME, SearchRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SearchResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/ws/de", name = "SearchResponse")
    public JAXBElement<SearchResponse> createSearchResponse(SearchResponse value) {
        return new JAXBElement<SearchResponse>(_SearchResponse_QNAME, SearchResponse.class, null, value);
    }
    
    
    /**
     * Create an instance of {@link BinaryNameValuePair }
     * 
     */
    public BinaryNameValuePair createBinaryNameValuePair() {
        return new BinaryNameValuePair();
    }

    /**
     * Create an instance of {@link BooleanNameValuePair }
     * 
     */
    public BooleanNameValuePair createBooleanNameValuePair() {
        return new BooleanNameValuePair();
    }

    /**
     * Create an instance of {@link DateTimeNameValuePair }
     * 
     */
    public DateTimeNameValuePair createDateTimeNameValuePair() {
        return new DateTimeNameValuePair();
    }

    /**
     * Create an instance of {@link DateNameValuePair }
     * 
     */
    public DateNameValuePair createDateNameValuePair() {
        return new DateNameValuePair();
    }

    /**
     * Create an instance of {@link DoubleNameValuePair }
     * 
     */
    public DoubleNameValuePair createDoubleNameValuePair() {
        return new DoubleNameValuePair();
    }

    /**
     * Create an instance of {@link IntegerNameValuePair }
     * 
     */
    public IntegerNameValuePair createIntegerNameValuePair() {
        return new IntegerNameValuePair();
    }

    /**
     * Create an instance of {@link MetaData }
     * 
     */
    public MetaData createMetaData() {
        return new MetaData();
    }

    /**
     * Create an instance of {@link MetaDataItem }
     * 
     */
    public MetaDataItem createMetaDataItem() {
        return new MetaDataItem();
    }

    /**
     * Create an instance of {@link NestedNameValuePair }
     * 
     */
    public NestedNameValuePair createNestedNameValuePair() {
        return new NestedNameValuePair();
    }

    /**
     * Create an instance of {@link OptionalNestedNameValuePair }
     * 
     */
    public OptionalNestedNameValuePair createOptionalNestedNameValuePair() {
        return new OptionalNestedNameValuePair();
    }

    /**
     * Create an instance of {@link StringNameValuePair }
     * 
     */
    public StringNameValuePair createStringNameValuePair() {
        return new StringNameValuePair();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BinaryNameValuePair }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BinaryNameValuePair }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/de/metadata", name = "Binary", substitutionHeadNamespace = "http://www.daon.com/de/metadata", substitutionHeadName = "NameValuePair")
    public JAXBElement<BinaryNameValuePair> createBinary(BinaryNameValuePair value) {
        return new JAXBElement<BinaryNameValuePair>(_Binary_QNAME, BinaryNameValuePair.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameValuePair }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NameValuePair }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/de/metadata", name = "NameValuePair")
    public JAXBElement<NameValuePair> createNameValuePair(NameValuePair value) {
        return new JAXBElement<NameValuePair>(_NameValuePair_QNAME, NameValuePair.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BooleanNameValuePair }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BooleanNameValuePair }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/de/metadata", name = "Boolean", substitutionHeadNamespace = "http://www.daon.com/de/metadata", substitutionHeadName = "NameValuePair")
    public JAXBElement<BooleanNameValuePair> createBoolean(BooleanNameValuePair value) {
        return new JAXBElement<BooleanNameValuePair>(_Boolean_QNAME, BooleanNameValuePair.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateTimeNameValuePair }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DateTimeNameValuePair }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/de/metadata", name = "DataTime", substitutionHeadNamespace = "http://www.daon.com/de/metadata", substitutionHeadName = "NameValuePair")
    public JAXBElement<DateTimeNameValuePair> createDataTime(DateTimeNameValuePair value) {
        return new JAXBElement<DateTimeNameValuePair>(_DataTime_QNAME, DateTimeNameValuePair.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateNameValuePair }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DateNameValuePair }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/de/metadata", name = "Date", substitutionHeadNamespace = "http://www.daon.com/de/metadata", substitutionHeadName = "NameValuePair")
    public JAXBElement<DateNameValuePair> createDate(DateNameValuePair value) {
        return new JAXBElement<DateNameValuePair>(_Date_QNAME, DateNameValuePair.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DoubleNameValuePair }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DoubleNameValuePair }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/de/metadata", name = "Double", substitutionHeadNamespace = "http://www.daon.com/de/metadata", substitutionHeadName = "NameValuePair")
    public JAXBElement<DoubleNameValuePair> createDouble(DoubleNameValuePair value) {
        return new JAXBElement<DoubleNameValuePair>(_Double_QNAME, DoubleNameValuePair.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IntegerNameValuePair }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link IntegerNameValuePair }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/de/metadata", name = "Integer", substitutionHeadNamespace = "http://www.daon.com/de/metadata", substitutionHeadName = "NameValuePair")
    public JAXBElement<IntegerNameValuePair> createInteger(IntegerNameValuePair value) {
        return new JAXBElement<IntegerNameValuePair>(_Integer_QNAME, IntegerNameValuePair.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetaData }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MetaData }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/de/metadata", name = "MetaData")
    public JAXBElement<MetaData> createMetaData(MetaData value) {
        return new JAXBElement<MetaData>(_MetaData_QNAME, MetaData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetaDataItem }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MetaDataItem }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/de/metadata", name = "MetaDataItem")
    public JAXBElement<MetaDataItem> createMetaDataItem(MetaDataItem value) {
        return new JAXBElement<MetaDataItem>(_MetaDataItem_QNAME, MetaDataItem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NestedNameValuePair }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NestedNameValuePair }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/de/metadata", name = "Nested", substitutionHeadNamespace = "http://www.daon.com/de/metadata", substitutionHeadName = "NameValuePair")
    public JAXBElement<NestedNameValuePair> createNested(NestedNameValuePair value) {
        return new JAXBElement<NestedNameValuePair>(_Nested_QNAME, NestedNameValuePair.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionalNestedNameValuePair }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OptionalNestedNameValuePair }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/de/metadata", name = "OptionalNestedNameValuePair")
    public JAXBElement<OptionalNestedNameValuePair> createOptionalNestedNameValuePair(OptionalNestedNameValuePair value) {
        return new JAXBElement<OptionalNestedNameValuePair>(_OptionalNestedNameValuePair_QNAME, OptionalNestedNameValuePair.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringNameValuePair }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StringNameValuePair }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/de/metadata", name = "String", substitutionHeadNamespace = "http://www.daon.com/de/metadata", substitutionHeadName = "NameValuePair")
    public JAXBElement<StringNameValuePair> createString(StringNameValuePair value) {
        return new JAXBElement<StringNameValuePair>(_String_QNAME, StringNameValuePair.class, null, value);
    }

}
