//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.14 at 09:18:33 PM ART 
//


package ar.com.macro.validacion.model.client.daonengine.identification.dto.soap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SearchAdjudication complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchAdjudication"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IdentityIdentifier" type="{http://www.daon.com/ws/de}IdentityIdentifier"/&gt;
 *         &lt;element name="OverallDecision" type="{http://www.daon.com/ws/de}SearchAdjudicationDecision"/&gt;
 *         &lt;element name="CandidateRank" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="SampleDecision" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://www.daon.com/ws/de}SearchAdjudicationDecision"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="TypeQualifier" type="{http://www.daon.com/ws/de}TypeQualifier"/&gt;
 *                   &lt;element name="UsageQualifier" type="{http://www.daon.com/ws/de}UsageQualifier" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchAdjudication", propOrder = {
    "identityIdentifier",
    "overallDecision",
    "candidateRank",
    "sampleDecision"
})
public class SearchAdjudication {

    @XmlElement(name = "IdentityIdentifier", required = true)
    protected IdentityIdentifier identityIdentifier;
    @XmlElement(name = "OverallDecision", required = true)
    protected SearchAdjudicationDecision overallDecision;
    @XmlElement(name = "CandidateRank")
    protected Integer candidateRank;
    @XmlElement(name = "SampleDecision")
    protected List<SearchAdjudication.SampleDecision> sampleDecision;

    /**
     * Gets the value of the identityIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityIdentifier }
     *     
     */
    public IdentityIdentifier getIdentityIdentifier() {
        return identityIdentifier;
    }

    /**
     * Sets the value of the identityIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityIdentifier }
     *     
     */
    public void setIdentityIdentifier(IdentityIdentifier value) {
        this.identityIdentifier = value;
    }

    /**
     * Gets the value of the overallDecision property.
     * 
     * @return
     *     possible object is
     *     {@link SearchAdjudicationDecision }
     *     
     */
    public SearchAdjudicationDecision getOverallDecision() {
        return overallDecision;
    }

    /**
     * Sets the value of the overallDecision property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchAdjudicationDecision }
     *     
     */
    public void setOverallDecision(SearchAdjudicationDecision value) {
        this.overallDecision = value;
    }

    /**
     * Gets the value of the candidateRank property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCandidateRank() {
        return candidateRank;
    }

    /**
     * Sets the value of the candidateRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCandidateRank(Integer value) {
        this.candidateRank = value;
    }

    /**
     * Gets the value of the sampleDecision property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sampleDecision property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSampleDecision().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SearchAdjudication.SampleDecision }
     * 
     * 
     */
    public List<SearchAdjudication.SampleDecision> getSampleDecision() {
        if (sampleDecision == null) {
            sampleDecision = new ArrayList<SearchAdjudication.SampleDecision>();
        }
        return this.sampleDecision;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://www.daon.com/ws/de}SearchAdjudicationDecision"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="TypeQualifier" type="{http://www.daon.com/ws/de}TypeQualifier"/&gt;
     *         &lt;element name="UsageQualifier" type="{http://www.daon.com/ws/de}UsageQualifier" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "typeQualifier",
        "usageQualifier"
    })
    public static class SampleDecision
        extends SearchAdjudicationDecision
    {

        @XmlElement(name = "TypeQualifier")
        protected int typeQualifier;
        @XmlElement(name = "UsageQualifier")
        protected Integer usageQualifier;

        /**
         * Gets the value of the typeQualifier property.
         * 
         */
        public int getTypeQualifier() {
            return typeQualifier;
        }

        /**
         * Sets the value of the typeQualifier property.
         * 
         */
        public void setTypeQualifier(int value) {
            this.typeQualifier = value;
        }

        /**
         * Gets the value of the usageQualifier property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getUsageQualifier() {
            return usageQualifier;
        }

        /**
         * Sets the value of the usageQualifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setUsageQualifier(Integer value) {
            this.usageQualifier = value;
        }

    }

}
