//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.14 at 09:18:33 PM ART 
//


package ar.com.macro.validacion.model.client.daonengine.identification.dto.soap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Perform Search operation on the presented BiometricData returning a Candidate List of zero
 *                     or more Identities. <p>
 * 
 * <p>Java class for SearchRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.daon.com/ws/de}AbstractRequest"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DomainIdentifier" type="{http://www.daon.com/ws/de}DomainIdentifier"/&gt;
 *         &lt;element name="SearchPolicyIdentifier" type="{http://www.daon.com/ws/de}PolicyIdentifier"/&gt;
 *         &lt;element name="TransformPolicyIdentifier" type="{http://www.daon.com/ws/de}PolicyIdentifier" minOccurs="0"/&gt;
 *         &lt;element name="GroupIdentifier" type="{http://www.daon.com/ws/de}GroupIdentifier" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Identity" type="{http://www.daon.com/ws/de}Identity"/&gt;
 *         &lt;element name="SearchParameters" type="{http://www.daon.com/ws/de}SearchParameters" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchRequest", propOrder = {
    "domainIdentifier",
    "searchPolicyIdentifier",
    "transformPolicyIdentifier",
    "groupIdentifier",
    "identity",
    "searchParameters"
})
public class SearchRequest
    extends AbstractRequest
{

    @XmlElement(name = "DomainIdentifier", required = true)
    protected DomainIdentifier domainIdentifier;
    @XmlElement(name = "SearchPolicyIdentifier", required = true)
    protected PolicyIdentifier searchPolicyIdentifier;
    @XmlElement(name = "TransformPolicyIdentifier")
    protected PolicyIdentifier transformPolicyIdentifier;
    @XmlElement(name = "GroupIdentifier")
    protected List<GroupIdentifier> groupIdentifier;
    @XmlElement(name = "Identity", required = true)
    protected Identity identity;
    @XmlElement(name = "SearchParameters")
    protected SearchParameters searchParameters;

    /**
     * Gets the value of the domainIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link DomainIdentifier }
     *     
     */
    public DomainIdentifier getDomainIdentifier() {
        return domainIdentifier;
    }

    /**
     * Sets the value of the domainIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainIdentifier }
     *     
     */
    public void setDomainIdentifier(DomainIdentifier value) {
        this.domainIdentifier = value;
    }

    /**
     * Gets the value of the searchPolicyIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyIdentifier }
     *     
     */
    public PolicyIdentifier getSearchPolicyIdentifier() {
        return searchPolicyIdentifier;
    }

    /**
     * Sets the value of the searchPolicyIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyIdentifier }
     *     
     */
    public void setSearchPolicyIdentifier(PolicyIdentifier value) {
        this.searchPolicyIdentifier = value;
    }

    /**
     * Gets the value of the transformPolicyIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyIdentifier }
     *     
     */
    public PolicyIdentifier getTransformPolicyIdentifier() {
        return transformPolicyIdentifier;
    }

    /**
     * Sets the value of the transformPolicyIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyIdentifier }
     *     
     */
    public void setTransformPolicyIdentifier(PolicyIdentifier value) {
        this.transformPolicyIdentifier = value;
    }

    /**
     * Gets the value of the groupIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the groupIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroupIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GroupIdentifier }
     * 
     * 
     */
    public List<GroupIdentifier> getGroupIdentifier() {
        if (groupIdentifier == null) {
            groupIdentifier = new ArrayList<GroupIdentifier>();
        }
        return this.groupIdentifier;
    }

    /**
     * Gets the value of the identity property.
     * 
     * @return
     *     possible object is
     *     {@link Identity }
     *     
     */
    public Identity getIdentity() {
        return identity;
    }

    /**
     * Sets the value of the identity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identity }
     *     
     */
    public void setIdentity(Identity value) {
        this.identity = value;
    }

    /**
     * Gets the value of the searchParameters property.
     * 
     * @return
     *     possible object is
     *     {@link SearchParameters }
     *     
     */
    public SearchParameters getSearchParameters() {
        return searchParameters;
    }

    /**
     * Sets the value of the searchParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchParameters }
     *     
     */
    public void setSearchParameters(SearchParameters value) {
        this.searchParameters = value;
    }

}
