//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.14 at 09:18:33 PM ART 
//


package ar.com.macro.validacion.model.client.daonengine.identification.dto.soap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Result for Verification performed with supplied BiometricData, against reference BiometricData held
 *                     by the system for the ClaimedIdentity.
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.daon.com/ws/de}AbstractDaonEngineResponse"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ResponseData" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="VerifyResult" type="{http://www.daon.com/ws/de}VerifyResult"/&gt;
 *                   &lt;element name="Score" type="{http://www.daon.com/ws/de}Score" minOccurs="0"/&gt;
 *                   &lt;element name="VerifyScore" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element ref="{http://www.daon.com/ws/de}AbstractScore" maxOccurs="unbounded"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="SampleScore" type="{http://www.daon.com/ws/de}SampleScore" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "responseData"
})
@XmlRootElement(name = "VerifyResponse")
public class VerifyResponse
    extends AbstractDaonEngineResponse
{

    @XmlElement(name = "ResponseData")
    protected VerifyResponse.ResponseData responseData;

    /**
     * Gets the value of the responseData property.
     * 
     * @return
     *     possible object is
     *     {@link VerifyResponse.ResponseData }
     *     
     */
    public VerifyResponse.ResponseData getResponseData() {
        return responseData;
    }

    /**
     * Sets the value of the responseData property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerifyResponse.ResponseData }
     *     
     */
    public void setResponseData(VerifyResponse.ResponseData value) {
        this.responseData = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="VerifyResult" type="{http://www.daon.com/ws/de}VerifyResult"/&gt;
     *         &lt;element name="Score" type="{http://www.daon.com/ws/de}Score" minOccurs="0"/&gt;
     *         &lt;element name="VerifyScore" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element ref="{http://www.daon.com/ws/de}AbstractScore" maxOccurs="unbounded"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="SampleScore" type="{http://www.daon.com/ws/de}SampleScore" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "verifyResult",
        "score",
        "verifyScore",
        "sampleScore"
    })
    public static class ResponseData {

        @XmlElement(name = "VerifyResult", required = true)
        @XmlSchemaType(name = "string")
        protected VerifyResult verifyResult;
        @XmlElement(name = "Score")
        protected String score;
        @XmlElement(name = "VerifyScore")
        protected VerifyResponse.ResponseData.VerifyScore verifyScore;
        @XmlElement(name = "SampleScore")
        protected List<SampleScore> sampleScore;

        /**
         * Gets the value of the verifyResult property.
         * 
         * @return
         *     possible object is
         *     {@link VerifyResult }
         *     
         */
        public VerifyResult getVerifyResult() {
            return verifyResult;
        }

        /**
         * Sets the value of the verifyResult property.
         * 
         * @param value
         *     allowed object is
         *     {@link VerifyResult }
         *     
         */
        public void setVerifyResult(VerifyResult value) {
            this.verifyResult = value;
        }

        /**
         * Gets the value of the score property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScore() {
            return score;
        }

        /**
         * Sets the value of the score property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScore(String value) {
            this.score = value;
        }

        /**
         * Gets the value of the verifyScore property.
         * 
         * @return
         *     possible object is
         *     {@link VerifyResponse.ResponseData.VerifyScore }
         *     
         */
        public VerifyResponse.ResponseData.VerifyScore getVerifyScore() {
            return verifyScore;
        }

        /**
         * Sets the value of the verifyScore property.
         * 
         * @param value
         *     allowed object is
         *     {@link VerifyResponse.ResponseData.VerifyScore }
         *     
         */
        public void setVerifyScore(VerifyResponse.ResponseData.VerifyScore value) {
            this.verifyScore = value;
        }

        /**
         * Gets the value of the sampleScore property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sampleScore property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSampleScore().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SampleScore }
         * 
         * 
         */
        public List<SampleScore> getSampleScore() {
            if (sampleScore == null) {
                sampleScore = new ArrayList<SampleScore>();
            }
            return this.sampleScore;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element ref="{http://www.daon.com/ws/de}AbstractScore" maxOccurs="unbounded"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "abstractScore"
        })
        public static class VerifyScore {

            @XmlElement(name = "AbstractScore", required = true)
            protected List<AbstractScore> abstractScore;

            /**
             * One or more Scores denoting the overall result for the verification as determined by the matcher.Gets the value of the abstractScore property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the abstractScore property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAbstractScore().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link AbstractScore }
             * 
             * 
             */
            public List<AbstractScore> getAbstractScore() {
                if (abstractScore == null) {
                    abstractScore = new ArrayList<AbstractScore>();
                }
                return this.abstractScore;
            }

        }

    }

}
