INSERT INTO db_macro_biometrics.application (application_id, path_regex) VALUES ('BlanqueoPinWeb', '[a-zA-Z0-9/]*/[a-zA-Z0-9/]*');
INSERT INTO db_macro_biometrics.application (application_id, path_regex) VALUES ('MandatoExtraccionAppId', '[a-zA-Z0-9/]*/[a-zA-Z0-9/]*');
INSERT INTO db_macro_biometrics.application (application_id, path_regex) VALUES ('FeDeVidaWeb', '[a-zA-Z0-9/]*/[a-zA-Z0-9/]*');
INSERT INTO db_macro_biometrics.application (application_id, path_regex) VALUES ('AppMiMacro', '[a-zA-Z0-9/]*/[a-zA-Z0-9/]*');
INSERT INTO db_macro_biometrics.application (application_id, path_regex) VALUES ('AppFull', '[a-zA-Z0-9/]*/[a-zA-Z0-9/]*');

INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('BlanqueoPinWeb', 'macro-validacion', 'configuracion-politica-identity-x', '{"politica-identity-x": {"local": "BioFace_OperacionesSimples","dev1": "BioFace_OperacionesSimples","stg1": "BioFace_OperacionesSimples","lab1": "BioFace_OperacionesSimples","test1": "BioFace_OperacionesSimples","pre-prd1": "BioFace_OperacionesSimples","pre-prd2": "BioFace_OperacionesSimples","prd1": "BioFace_OperacionesSimples","prd2": "BioFace_OperacionesSimples"}}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('MandatoExtraccionAppId', 'macro-validacion', 'configuracion-politica-identity-x', '{"politica-identity-x": {"local": "BioFace_OperacionesSimples","dev1": "BioFace_OperacionesSimples","stg1": "BioFace_OperacionesSimples","lab1": "BioFace_OperacionesSimples","test1": "BioFace_OperacionesSimples","pre-prd1": "BioFace_OperacionesSimples","pre-prd2": "BioFace_OperacionesSimples","prd1": "BioFace_OperacionesSimples","prd2": "BioFace_OperacionesSimples"}}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('SupervivenciaWeb', 'macro-validacion', 'configuracion-politica-identity-x', '{"politica-identity-x": {"local": "BioFace_OperacionesSimples","dev1": "BioFace_OperacionesSimples","stg1": "BioFace_OperacionesSimples","lab1": "BioFace_OperacionesSimples","test1": "BioFace_OperacionesSimples","pre-prd1": "BioFace_OperacionesSimples","pre-prd2": "BioFace_OperacionesSimples","prd1": "BioFace_OperacionesSimples","prd2": "BioFace_OperacionesSimples"}}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('FeDeVidaWeb', 'macro-validacion', 'configuracion-politica-identity-x', '{"politica-identity-x": {"local": "BioFace_OperacionesSimples","dev1": "BioFace_OperacionesSimples","stg1": "BioFace_OperacionesSimples","lab1": "BioFace_OperacionesSimples","test1": "BioFace_OperacionesSimples","pre-prd1": "BioFace_OperacionesSimples","pre-prd2": "BioFace_OperacionesSimples","prd1": "BioFace_OperacionesSimples","prd2": "BioFace_OperacionesSimples"}}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('GuruClavesApplicationId', 'macro-validacion', 'configuracion-politica-identity-x', '{"politica-identity-x": {"local": "BioFace_GuruSucursal","dev1": "BioFace_GuruSucursal","stg1": "BioFace_GuruSucursal","lab1": "BioFace_GuruSucursal","test1": "BioFace_GuruSucursal","pre-prd1": "BioFace_GuruSucursal","pre-prd2": "BioFace_GuruSucursal","prd1": "BioFace_GuruSucursal","prd2": "BioFace_GuruSucursal"}}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('AppMiMacro', 'macro-validacion', 'configuracion-politica-identity-x', '{"politica-identity-x": {"local": "BioFace_APP_MiMacro","dev1": "BioFace_APP_MiMacro","stg1": "BioFace_APP_MiMacro","lab1": "BioFace_APP_MiMacro","test1": "BioFace_APP_MiMacro","pre-prd1": "BioFace_APP_MiMacro","pre-prd2": "BioFace_APP_MiMacro","prd1": "BioFace_APP_MiMacro","prd2": "BioFace_APP_MiMacro"}}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('AppFull', 'macro-validacion', 'configuracion-politica-identity-x', '{"politica-identity-x": {"local": "BioFace_APP_Full","dev1": "BioFace_APP_Full","stg1": "BioFace_APP_Full","lab1": "BioFace_APP_Full","test1": "BioFace_APP_Full","pre-prd1": "BioFace_APP_Full","pre-prd2": "BioFace_APP_Full","prd1": "BioFace_APP_Full","prd2": "BioFace_APP_Full"}}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('BlanqueoPinWeb', 'macro-validacion', 'configuracion-aplicacion-identity-x', '{ "aplicacion-identity-x" : { "local" : "banco_macro_app", "dev1" : "banco_macro_app", "stg1" : "banco_macro_app", "lab1" : "banco_macro_app", "test1" : "banco_macro_app", "pre-prd1" : "banco_macro_app", "pre-prd2" : "banco_macro_app", "prd1" : "banco_macro_app", "prd2" : "banco_macro_app" }}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('MandatoExtraccionAppId', 'macro-validacion', 'configuracion-aplicacion-identity-x', '{ "aplicacion-identity-x" : { "local" : "banco_macro_app", "dev1" : "banco_macro_app", "stg1" : "banco_macro_app", "lab1" : "banco_macro_app", "test1" : "banco_macro_app", "pre-prd1" : "banco_macro_app", "pre-prd2" : "banco_macro_app", "prd1" : "banco_macro_app", "prd2" : "banco_macro_app" }}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('SupervivenciaWeb', 'macro-validacion', 'configuracion-aplicacion-identity-x', '{ "aplicacion-identity-x" : { "local" : "banco_macro_app", "dev1" : "banco_macro_app", "stg1" : "banco_macro_app", "lab1" : "banco_macro_app", "test1" : "banco_macro_app", "pre-prd1" : "banco_macro_app", "pre-prd2" : "banco_macro_app", "prd1" : "banco_macro_app", "prd2" : "banco_macro_app" }}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('FeDeVidaWeb', 'macro-validacion', 'configuracion-aplicacion-identity-x', '{ "aplicacion-identity-x" : { "local" : "banco_macro_app", "dev1" : "banco_macro_app", "stg1" : "banco_macro_app", "lab1" : "banco_macro_app", "test1" : "banco_macro_app", "pre-prd1" : "banco_macro_app", "pre-prd2" : "banco_macro_app", "prd1" : "banco_macro_app", "prd2" : "banco_macro_app" }}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('GuruClavesApplicationId', 'macro-validacion', 'configuracion-aplicacion-identity-x', '{ "aplicacion-identity-x" : { "local" : "banco_macro_app", "dev1" : "banco_macro_app", "stg1" : "banco_macro_app", "lab1" : "banco_macro_app", "test1" : "banco_macro_app", "pre-prd1" : "banco_macro_app", "pre-prd2" : "banco_macro_app", "prd1" : "banco_macro_app", "prd2" : "banco_macro_app" }}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('AppMiMacro', 'macro-validacion', 'configuracion-aplicacion-identity-x', '{ "aplicacion-identity-x" : { "local" : "banco_macro_app", "dev1" : "banco_macro_app", "stg1" : "banco_macro_app", "lab1" : "banco_macro_app", "test1" : "banco_macro_app", "pre-prd1" : "banco_macro_app", "pre-prd2" : "banco_macro_app", "prd1" : "banco_macro_app", "prd2" : "banco_macro_app" }}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('AppFull', 'macro-validacion', 'configuracion-aplicacion-identity-x', '{ "aplicacion-identity-x" : { "local" : "banco_macro_app", "dev1" : "banco_macro_app", "stg1" : "banco_macro_app", "lab1" : "banco_macro_app", "test1" : "banco_macro_app", "pre-prd1" : "banco_macro_app", "pre-prd2" : "banco_macro_app", "prd1" : "banco_macro_app", "prd2" : "banco_macro_app" }}', now(), now());

