INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('EnrolamientoApp', 'macro-validacion', 'configuracion-politica-3dfl-identity-x', '{"politica-identity-x": {"local": "test","dev1": "test","stg1": "test","lab1": "test","test1": "test","pre-prd1": "test","pre-prd2": "test","prd1": "test","prd2": "test"}}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('BlanqueoPinWeb', 'macro-validacion', 'configuracion-politica-3dfl-identity-x', '{"politica-identity-x": {"local": "test","dev1": "test","stg1": "test","lab1": "test","test1": "test","pre-prd1": "test","pre-prd2": "test","prd1": "test","prd2": "test"}}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('MandatoExtraccionAppId', 'macro-validacion', 'configuracion-politica-3dfl-identity-x', '{"politica-identity-x": {"local": "test","dev1": "test","stg1": "test","lab1": "test","test1": "test","pre-prd1": "test","pre-prd2": "test","prd1": "test","prd2": "test"}}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('SupervivenciaWeb', 'macro-validacion', 'configuracion-politica-3dfl-identity-x', '{"politica-identity-x": {"local": "test","dev1": "test","stg1": "test","lab1": "test","test1": "test","pre-prd1": "test","pre-prd2": "test","prd1": "test","prd2": "test"}}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('FeDeVidaWeb', 'macro-validacion', 'configuracion-politica-3dfl-identity-x', '{"politica-identity-x": {"local": "test","dev1": "test","stg1": "test","lab1": "test","test1": "test","pre-prd1": "test","pre-prd2": "test","prd1": "test","prd2": "test"}}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('GuruClavesApplicationId', 'macro-validacion', 'configuracion-politica-3dfl-identity-x', '{"politica-identity-x": {"local": "test","dev1": "test","stg1": "test","lab1": "test","test1": "test","pre-prd1": "test","pre-prd2": "test","prd1": "test","prd2": "test"}}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('AppMiMacro', 'macro-validacion', 'configuracion-politica-3dfl-identity-x', '{"politica-identity-x": {"local": "test","dev1": "test","stg1": "test","lab1": "test","test1": "test","pre-prd1": "test","pre-prd2": "test","prd1": "test","prd2": "test"}}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('AppFull', 'macro-validacion', 'configuracion-politica-3dfl-identity-x', '{"politica-identity-x": {"local": "test","dev1": "test","stg1": "test","lab1": "test","test1": "test","pre-prd1": "test","pre-prd2": "test","prd1": "test","prd2": "test"}}', now(), now());

INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('EnrolamientoApp', 'macro-validacion', 'configuracion-politica-evaluacion-identity-x', '{"aplicacion-identity-x": {"local": "globantEvalutationtest","dev1": "globantEvalutationtest","stg1": "globantEvalutationtest","lab1": "globantEvalutationtest","test1": "globantEvalutationtest","pre-prd1": "globantEvalutationtest","pre-prd2": "globantEvalutationtest","prd1": "globantEvalutationtest","prd2": "globantEvalutationtest"}}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('BlanqueoPinWeb', 'macro-validacion', 'configuracion-politica-evaluacion-identity-x', '{"aplicacion-identity-x": {"local": "globantEvalutationtest","dev1": "globantEvalutationtest","stg1": "globantEvalutationtest","lab1": "globantEvalutationtest","test1": "globantEvalutationtest","pre-prd1": "globantEvalutationtest","pre-prd2": "globantEvalutationtest","prd1": "globantEvalutationtest","prd2": "globantEvalutationtest"}}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('MandatoExtraccionAppId', 'macro-validacion', 'configuracion-politica-evaluacion-identity-x', '{"aplicacion-identity-x": {"local": "globantEvalutationtest","dev1": "globantEvalutationtest","stg1": "globantEvalutationtest","lab1": "globantEvalutationtest","test1": "globantEvalutationtest","pre-prd1": "globantEvalutationtest","pre-prd2": "globantEvalutationtest","prd1": "globantEvalutationtest","prd2": "globantEvalutationtest"}}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('SupervivenciaWeb', 'macro-validacion', 'configuracion-politica-evaluacion-identity-x', '{"aplicacion-identity-x": {"local": "globantEvalutationtest","dev1": "globantEvalutationtest","stg1": "globantEvalutationtest","lab1": "globantEvalutationtest","test1": "globantEvalutationtest","pre-prd1": "globantEvalutationtest","pre-prd2": "globantEvalutationtest","prd1": "globantEvalutationtest","prd2": "globantEvalutationtest"}}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('FeDeVidaWeb', 'macro-validacion', 'configuracion-politica-evaluacion-identity-x', '{"aplicacion-identity-x": {"local": "globantEvalutationtest","dev1": "globantEvalutationtest","stg1": "globantEvalutationtest","lab1": "globantEvalutationtest","test1": "globantEvalutationtest","pre-prd1": "globantEvalutationtest","pre-prd2": "globantEvalutationtest","prd1": "globantEvalutationtest","prd2": "globantEvalutationtest"}}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('GuruClavesApplicationId', 'macro-validacion', 'configuracion-politica-evaluacion-identity-x', '{"aplicacion-identity-x": {"local": "globantEvalutationtest","dev1": "globantEvalutationtest","stg1": "globantEvalutationtest","lab1": "globantEvalutationtest","test1": "globantEvalutationtest","pre-prd1": "globantEvalutationtest","pre-prd2": "globantEvalutationtest","prd1": "globantEvalutationtest","prd2": "globantEvalutationtest"}}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('AppMiMacro', 'macro-validacion', 'configuracion-politica-evaluacion-identity-x', '{"aplicacion-identity-x": {"local": "globantEvalutationtest","dev1": "globantEvalutationtest","stg1": "globantEvalutationtest","lab1": "globantEvalutationtest","test1": "globantEvalutationtest","pre-prd1": "globantEvalutationtest","pre-prd2": "globantEvalutationtest","prd1": "globantEvalutationtest","prd2": "globantEvalutationtest"}}', now(), now());
INSERT INTO db_macro_biometrics.mscompositeparamconfig (application_id, microservice_id, name, value, creationdate, modificationdate) VALUES ('AppFull', 'macro-validacion', 'configuracion-politica-evaluacion-identity-x', '{"aplicacion-identity-x": {"local": "globantEvalutationtest","dev1": "globantEvalutationtest","stg1": "globantEvalutationtest","lab1": "globantEvalutationtest","test1": "globantEvalutationtest","pre-prd1": "globantEvalutationtest","pre-prd2": "globantEvalutationtest","prd1": "globantEvalutationtest","prd2": "globantEvalutationtest"}}', now(), now());

