INSERT INTO mscompositeparamconfig (application_id,microservice_id,name,value,creationdate,modificationdate) 
VALUES
	 ('BlanqueoPinWeb','macro-validacion','configuracion-huellas-daon-engine','{ "manoDerecha" : { "pulgar" : 21, "indice" : 22, "mayor" : 23, "anular" : 24, "menique" : 25}, "manoIzquierda" : { "pulgar" : 15, "indice" : 14, "mayor" : 13, "anular" : 12, "menique" : 11 }}', now(), now()),
	 ('BlanqueoPinWeb','macro-validacion','configuracion-huellas-renaper','{ "manoDerecha" : { "pulgar" : 1, "indice" : 2, "mayor" : 3, "anular" : 4, "menique" : 5}, "manoIzquierda" : { "pulgar" : 6, "indice" : 7, "mayor" : 8, "anular" : 9, "menique" : 10 }}', now(), now()),	 
	 ('MandatoExtraccionAppId','macro-validacion','configuracion-huellas-daon-engine','{ "manoDerecha" : { "pulgar" : 21, "indice" : 22, "mayor" : 23, "anular" : 24, "menique" : 25}, "manoIzquierda" : { "pulgar" : 15, "indice" : 14, "mayor" : 13, "anular" : 12, "menique" : 11 }}', now(), now()),
	 ('MandatoExtraccionAppId','macro-validacion','configuracion-huellas-renaper','{ "manoDerecha" : { "pulgar" : 1, "indice" : 2, "mayor" : 3, "anular" : 4, "menique" : 5}, "manoIzquierda" : { "pulgar" : 6, "indice" : 7, "mayor" : 8, "anular" : 9, "menique" : 10 }}', now(), now()),	 
	 ('SupervivenciaWeb','macro-validacion','configuracion-huellas-daon-engine','{ "manoDerecha" : { "pulgar" : 21, "indice" : 22, "mayor" : 23, "anular" : 24, "menique" : 25}, "manoIzquierda" : { "pulgar" : 15, "indice" : 14, "mayor" : 13, "anular" : 12, "menique" : 11 }}', now(), now()),
	 ('SupervivenciaWeb','macro-validacion','configuracion-huellas-renaper','{ "manoDerecha" : { "pulgar" : 1, "indice" : 2, "mayor" : 3, "anular" : 4, "menique" : 5}, "manoIzquierda" : { "pulgar" : 6, "indice" : 7, "mayor" : 8, "anular" : 9, "menique" : 10 }}', now(), now()),
	 ('FeDeVidaWeb','macro-validacion','configuracion-huellas-daon-engine','{ "manoDerecha" : { "pulgar" : 21, "indice" : 22, "mayor" : 23, "anular" : 24, "menique" : 25}, "manoIzquierda" : { "pulgar" : 15, "indice" : 14, "mayor" : 13, "anular" : 12, "menique" : 11 }}', now(), now()),
	 ('FeDeVidaWeb','macro-validacion','configuracion-huellas-renaper','{ "manoDerecha" : { "pulgar" : 1, "indice" : 2, "mayor" : 3, "anular" : 4, "menique" : 5}, "manoIzquierda" : { "pulgar" : 6, "indice" : 7, "mayor" : 8, "anular" : 9, "menique" : 10 }}', now(), now()),	 
	 ('AppFull','macro-validacion','configuracion-huellas-daon-engine','{ "manoDerecha" : { "pulgar" : 21, "indice" : 22, "mayor" : 23, "anular" : 24, "menique" : 25}, "manoIzquierda" : { "pulgar" : 15, "indice" : 14, "mayor" : 13, "anular" : 12, "menique" : 11 }}', now(), now()),
	 ('AppFull','macro-validacion','configuracion-huellas-renaper','{ "manoDerecha" : { "pulgar" : 1, "indice" : 2, "mayor" : 3, "anular" : 4, "menique" : 5}, "manoIzquierda" : { "pulgar" : 6, "indice" : 7, "mayor" : 8, "anular" : 9, "menique" : 10 }}', now(), now()),	 
	 ('AppMiMacro','macro-validacion','configuracion-huellas-daon-engine','{ "manoDerecha" : { "pulgar" : 21, "indice" : 22, "mayor" : 23, "anular" : 24, "menique" : 25}, "manoIzquierda" : { "pulgar" : 15, "indice" : 14, "mayor" : 13, "anular" : 12, "menique" : 11 }}', now(), now()),
	 ('AppMiMacro','macro-validacion','configuracion-huellas-renaper','{ "manoDerecha" : { "pulgar" : 1, "indice" : 2, "mayor" : 3, "anular" : 4, "menique" : 5}, "manoIzquierda" : { "pulgar" : 6, "indice" : 7, "mayor" : 8, "anular" : 9, "menique" : 10 }}', now(), now())
	 ;
