apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: biometria-ns
spec:
  type: ExternalName
  externalName: biometria-db-dev.c09l2m5riqoc.us-east-1.rds.amazonaws.com
  selector: {}
