//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.17 at 02:10:31 PM ART 
//


package ar.com.macro.validacion.model.client.daonengine.systemmanagement.dto.soap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * An Identity's biographic data.
 * 
 * <p>Java class for BiographicData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BiographicData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="StringItem" type="{http://www.daon.com/ws/de}StringItem" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="LongItem" type="{http://www.daon.com/ws/de}LongItem" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="DoubleItem" type="{http://www.daon.com/ws/de}DoubleItem" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="DateItem" type="{http://www.daon.com/ws/de}DateItem" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="TimestampItem" type="{http://www.daon.com/ws/de}TimestampItem" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ExtendedStringItem" type="{http://www.daon.com/ws/de}ExtendedStringItem" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ExtendedBinaryItem" type="{http://www.daon.com/ws/de}ExtendedBinaryItem" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BiographicData", propOrder = {
    "stringItem",
    "longItem",
    "doubleItem",
    "dateItem",
    "timestampItem",
    "extendedStringItem",
    "extendedBinaryItem"
})
public class BiographicData {

    @XmlElement(name = "StringItem")
    protected List<StringItem> stringItem;
    @XmlElement(name = "LongItem")
    protected List<LongItem> longItem;
    @XmlElement(name = "DoubleItem")
    protected List<DoubleItem> doubleItem;
    @XmlElement(name = "DateItem")
    protected List<DateItem> dateItem;
    @XmlElement(name = "TimestampItem")
    protected List<TimestampItem> timestampItem;
    @XmlElement(name = "ExtendedStringItem")
    protected List<ExtendedStringItem> extendedStringItem;
    @XmlElement(name = "ExtendedBinaryItem")
    protected List<ExtendedBinaryItem> extendedBinaryItem;

    /**
     * Gets the value of the stringItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stringItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStringItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StringItem }
     * 
     * 
     */
    public List<StringItem> getStringItem() {
        if (stringItem == null) {
            stringItem = new ArrayList<StringItem>();
        }
        return this.stringItem;
    }

    /**
     * Gets the value of the longItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the longItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLongItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LongItem }
     * 
     * 
     */
    public List<LongItem> getLongItem() {
        if (longItem == null) {
            longItem = new ArrayList<LongItem>();
        }
        return this.longItem;
    }

    /**
     * Gets the value of the doubleItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the doubleItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDoubleItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DoubleItem }
     * 
     * 
     */
    public List<DoubleItem> getDoubleItem() {
        if (doubleItem == null) {
            doubleItem = new ArrayList<DoubleItem>();
        }
        return this.doubleItem;
    }

    /**
     * Gets the value of the dateItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dateItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDateItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateItem }
     * 
     * 
     */
    public List<DateItem> getDateItem() {
        if (dateItem == null) {
            dateItem = new ArrayList<DateItem>();
        }
        return this.dateItem;
    }

    /**
     * Gets the value of the timestampItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timestampItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTimestampItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimestampItem }
     * 
     * 
     */
    public List<TimestampItem> getTimestampItem() {
        if (timestampItem == null) {
            timestampItem = new ArrayList<TimestampItem>();
        }
        return this.timestampItem;
    }

    /**
     * Gets the value of the extendedStringItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extendedStringItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtendedStringItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtendedStringItem }
     * 
     * 
     */
    public List<ExtendedStringItem> getExtendedStringItem() {
        if (extendedStringItem == null) {
            extendedStringItem = new ArrayList<ExtendedStringItem>();
        }
        return this.extendedStringItem;
    }

    /**
     * Gets the value of the extendedBinaryItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extendedBinaryItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtendedBinaryItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtendedBinaryItem }
     * 
     * 
     */
    public List<ExtendedBinaryItem> getExtendedBinaryItem() {
        if (extendedBinaryItem == null) {
            extendedBinaryItem = new ArrayList<ExtendedBinaryItem>();
        }
        return this.extendedBinaryItem;
    }

}
