//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.17 at 02:10:31 PM ART 
//


package ar.com.macro.validacion.model.client.daonengine.systemmanagement.dto.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information about a biometric item.
 * 
 * <p>Java class for BiometricItemInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BiometricItemInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TypeQualifier" type="{http://www.daon.com/ws/de}TypeQualifier"/&gt;
 *         &lt;element name="UsageQualifier" type="{http://www.daon.com/ws/de}UsageQualifier"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BiometricItemInfo", propOrder = {
    "typeQualifier",
    "usageQualifier"
})
public class BiometricItemInfo {

    @XmlElement(name = "TypeQualifier")
    protected int typeQualifier;
    @XmlElement(name = "UsageQualifier")
    protected int usageQualifier;

    /**
     * Gets the value of the typeQualifier property.
     * 
     */
    public int getTypeQualifier() {
        return typeQualifier;
    }

    /**
     * Sets the value of the typeQualifier property.
     * 
     */
    public void setTypeQualifier(int value) {
        this.typeQualifier = value;
    }

    /**
     * Gets the value of the usageQualifier property.
     * 
     */
    public int getUsageQualifier() {
        return usageQualifier;
    }

    /**
     * Sets the value of the usageQualifier property.
     * 
     */
    public void setUsageQualifier(int value) {
        this.usageQualifier = value;
    }

}
