//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.17 at 02:10:31 PM ART 
//


package ar.com.macro.validacion.model.client.daonengine.systemmanagement.dto.soap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines a single element for encapsulating the data
 *             	associated with an Identity. Includes the Identity's
 *             	CoreData, BiographicData, BiometricData and
 *             	GroupMembership details.
 * 
 * <p>Java class for Identity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Identity"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IdentityIdentifier" type="{http://www.daon.com/ws/de}IdentityIdentifier" minOccurs="0"/&gt;
 *         &lt;element name="CoreData" type="{http://www.daon.com/ws/de}CoreData" minOccurs="0"/&gt;
 *         &lt;element name="BiographicData" type="{http://www.daon.com/ws/de}BiographicData" minOccurs="0"/&gt;
 *         &lt;element name="BiometricData" type="{http://www.daon.com/ws/de}BiometricDataElement" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="SecureBiometricData" type="{http://www.daon.com/ws/de}SecureEnvelope" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="GroupMembership" type="{http://www.daon.com/ws/de}GroupMembership" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Identity", propOrder = {
    "identityIdentifier",
    "coreData",
    "biographicData",
    "biometricData",
    "secureBiometricData",
    "groupMembership"
})
public class Identity {

    @XmlElement(name = "IdentityIdentifier")
    protected IdentityIdentifier identityIdentifier;
    @XmlElement(name = "CoreData")
    protected CoreData coreData;
    @XmlElement(name = "BiographicData")
    protected BiographicData biographicData;
    @XmlElement(name = "BiometricData")
    protected List<BiometricDataElement> biometricData;
    @XmlElement(name = "SecureBiometricData")
    protected List<SecureEnvelope> secureBiometricData;
    @XmlElement(name = "GroupMembership")
    protected List<GroupMembership> groupMembership;

    /**
     * Gets the value of the identityIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityIdentifier }
     *     
     */
    public IdentityIdentifier getIdentityIdentifier() {
        return identityIdentifier;
    }

    /**
     * Sets the value of the identityIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityIdentifier }
     *     
     */
    public void setIdentityIdentifier(IdentityIdentifier value) {
        this.identityIdentifier = value;
    }

    /**
     * Gets the value of the coreData property.
     * 
     * @return
     *     possible object is
     *     {@link CoreData }
     *     
     */
    public CoreData getCoreData() {
        return coreData;
    }

    /**
     * Sets the value of the coreData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoreData }
     *     
     */
    public void setCoreData(CoreData value) {
        this.coreData = value;
    }

    /**
     * Gets the value of the biographicData property.
     * 
     * @return
     *     possible object is
     *     {@link BiographicData }
     *     
     */
    public BiographicData getBiographicData() {
        return biographicData;
    }

    /**
     * Sets the value of the biographicData property.
     * 
     * @param value
     *     allowed object is
     *     {@link BiographicData }
     *     
     */
    public void setBiographicData(BiographicData value) {
        this.biographicData = value;
    }

    /**
     * Gets the value of the biometricData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the biometricData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBiometricData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BiometricDataElement }
     * 
     * 
     */
    public List<BiometricDataElement> getBiometricData() {
        if (biometricData == null) {
            biometricData = new ArrayList<BiometricDataElement>();
        }
        return this.biometricData;
    }

    /**
     * Gets the value of the secureBiometricData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the secureBiometricData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSecureBiometricData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SecureEnvelope }
     * 
     * 
     */
    public List<SecureEnvelope> getSecureBiometricData() {
        if (secureBiometricData == null) {
            secureBiometricData = new ArrayList<SecureEnvelope>();
        }
        return this.secureBiometricData;
    }

    /**
     * Gets the value of the groupMembership property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the groupMembership property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroupMembership().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GroupMembership }
     * 
     * 
     */
    public List<GroupMembership> getGroupMembership() {
        if (groupMembership == null) {
            groupMembership = new ArrayList<GroupMembership>();
        }
        return this.groupMembership;
    }

}
