//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.17 at 02:10:31 PM ART 
//


package ar.com.macro.validacion.model.client.daonengine.systemmanagement.dto.soap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Returns details of Audits matching the request
 *                 	SummaryAudit Selection Criteria.
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.daon.com/ws/de}AbstractDaonEngineResponse"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ResponseData" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="SummaryAudit" type="{http://www.daon.com/ws/de}SummaryAudit" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="CompleteListReturned" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="CompleteListSize" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "responseData"
})
@XmlRootElement(name = "ListSummaryAuditsResponse")
public class ListSummaryAuditsResponse
    extends AbstractDaonEngineResponse
{

    @XmlElement(name = "ResponseData")
    protected ListSummaryAuditsResponse.ResponseData responseData;

    /**
     * Gets the value of the responseData property.
     * 
     * @return
     *     possible object is
     *     {@link ListSummaryAuditsResponse.ResponseData }
     *     
     */
    public ListSummaryAuditsResponse.ResponseData getResponseData() {
        return responseData;
    }

    /**
     * Sets the value of the responseData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListSummaryAuditsResponse.ResponseData }
     *     
     */
    public void setResponseData(ListSummaryAuditsResponse.ResponseData value) {
        this.responseData = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="SummaryAudit" type="{http://www.daon.com/ws/de}SummaryAudit" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="CompleteListReturned" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="CompleteListSize" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "summaryAudit",
        "completeListReturned",
        "completeListSize"
    })
    public static class ResponseData {

        @XmlElement(name = "SummaryAudit")
        protected List<SummaryAudit> summaryAudit;
        @XmlElement(name = "CompleteListReturned")
        protected boolean completeListReturned;
        @XmlElement(name = "CompleteListSize")
        protected int completeListSize;

        /**
         * Gets the value of the summaryAudit property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the summaryAudit property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSummaryAudit().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SummaryAudit }
         * 
         * 
         */
        public List<SummaryAudit> getSummaryAudit() {
            if (summaryAudit == null) {
                summaryAudit = new ArrayList<SummaryAudit>();
            }
            return this.summaryAudit;
        }

        /**
         * Gets the value of the completeListReturned property.
         * 
         */
        public boolean isCompleteListReturned() {
            return completeListReturned;
        }

        /**
         * Sets the value of the completeListReturned property.
         * 
         */
        public void setCompleteListReturned(boolean value) {
            this.completeListReturned = value;
        }

        /**
         * Gets the value of the completeListSize property.
         * 
         */
        public int getCompleteListSize() {
            return completeListSize;
        }

        /**
         * Sets the value of the completeListSize property.
         * 
         */
        public void setCompleteListSize(int value) {
            this.completeListSize = value;
        }

    }

}
