//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.17 at 02:10:31 PM ART 
//


package ar.com.macro.validacion.model.client.daonengine.systemmanagement.dto.soap;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.daon.ws.de package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AbstractScore_QNAME = new QName("http://www.daon.com/ws/de", "AbstractScore");
    private final static QName _FMR_QNAME = new QName("http://www.daon.com/ws/de", "FMR");
    private final static QName _RawScore_QNAME = new QName("http://www.daon.com/ws/de", "RawScore");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.daon.ws.de
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetDomainDescriptionResponse }
     * 
     */
    public GetDomainDescriptionResponse createGetDomainDescriptionResponse() {
        return new GetDomainDescriptionResponse();
    }

    /**
     * Create an instance of {@link ListDomainsResponse }
     * 
     */
    public ListDomainsResponse createListDomainsResponse() {
        return new ListDomainsResponse();
    }

    /**
     * Create an instance of {@link ListSummaryAuditsResponse }
     * 
     */
    public ListSummaryAuditsResponse createListSummaryAuditsResponse() {
        return new ListSummaryAuditsResponse();
    }

    /**
     * Create an instance of {@link RecordSummaryAuditResponse }
     * 
     */
    public RecordSummaryAuditResponse createRecordSummaryAuditResponse() {
        return new RecordSummaryAuditResponse();
    }

    /**
     * Create an instance of {@link VerifyParameters }
     * 
     */
    public VerifyParameters createVerifyParameters() {
        return new VerifyParameters();
    }

    /**
     * Create an instance of {@link VerificationAdjudication }
     * 
     */
    public VerificationAdjudication createVerificationAdjudication() {
        return new VerificationAdjudication();
    }

    /**
     * Create an instance of {@link SearchParameters }
     * 
     */
    public SearchParameters createSearchParameters() {
        return new SearchParameters();
    }

    /**
     * Create an instance of {@link SearchAdjudication }
     * 
     */
    public SearchAdjudication createSearchAdjudication() {
        return new SearchAdjudication();
    }

    /**
     * Create an instance of {@link DomainDetails }
     * 
     */
    public DomainDetails createDomainDetails() {
        return new DomainDetails();
    }

    /**
     * Create an instance of {@link Candidate }
     * 
     */
    public Candidate createCandidate() {
        return new Candidate();
    }

    /**
     * Create an instance of {@link BiometricDataElement }
     * 
     */
    public BiometricDataElement createBiometricDataElement() {
        return new BiometricDataElement();
    }

    /**
     * Create an instance of {@link FMR }
     * 
     */
    public FMR createFMR() {
        return new FMR();
    }

    /**
     * Create an instance of {@link GetDomainDescriptionRequest }
     * 
     */
    public GetDomainDescriptionRequest createGetDomainDescriptionRequest() {
        return new GetDomainDescriptionRequest();
    }

    /**
     * Create an instance of {@link GenericRequestParameters }
     * 
     */
    public GenericRequestParameters createGenericRequestParameters() {
        return new GenericRequestParameters();
    }

    /**
     * Create an instance of {@link CustomParameters }
     * 
     */
    public CustomParameters createCustomParameters() {
        return new CustomParameters();
    }

    /**
     * Create an instance of {@link DomainIdentifier }
     * 
     */
    public DomainIdentifier createDomainIdentifier() {
        return new DomainIdentifier();
    }

    /**
     * Create an instance of {@link ResponseStatus }
     * 
     */
    public ResponseStatus createResponseStatus() {
        return new ResponseStatus();
    }

    /**
     * Create an instance of {@link GetDomainDescriptionResponse.ResponseData }
     * 
     */
    public GetDomainDescriptionResponse.ResponseData createGetDomainDescriptionResponseResponseData() {
        return new GetDomainDescriptionResponse.ResponseData();
    }

    /**
     * Create an instance of {@link ListDomainsRequest }
     * 
     */
    public ListDomainsRequest createListDomainsRequest() {
        return new ListDomainsRequest();
    }

    /**
     * Create an instance of {@link ListDomainsResponse.ResponseData }
     * 
     */
    public ListDomainsResponse.ResponseData createListDomainsResponseResponseData() {
        return new ListDomainsResponse.ResponseData();
    }

    /**
     * Create an instance of {@link ListSummaryAuditsRequest }
     * 
     */
    public ListSummaryAuditsRequest createListSummaryAuditsRequest() {
        return new ListSummaryAuditsRequest();
    }

    /**
     * Create an instance of {@link ReturnSetCriteria }
     * 
     */
    public ReturnSetCriteria createReturnSetCriteria() {
        return new ReturnSetCriteria();
    }

    /**
     * Create an instance of {@link ListSummaryAuditsResponse.ResponseData }
     * 
     */
    public ListSummaryAuditsResponse.ResponseData createListSummaryAuditsResponseResponseData() {
        return new ListSummaryAuditsResponse.ResponseData();
    }

    /**
     * Create an instance of {@link RawScore }
     * 
     */
    public RawScore createRawScore() {
        return new RawScore();
    }

    /**
     * Create an instance of {@link RecordSummaryAuditRequest }
     * 
     */
    public RecordSummaryAuditRequest createRecordSummaryAuditRequest() {
        return new RecordSummaryAuditRequest();
    }

    /**
     * Create an instance of {@link SummaryAudit }
     * 
     */
    public SummaryAudit createSummaryAudit() {
        return new SummaryAudit();
    }

    /**
     * Create an instance of {@link RecordSummaryAuditResponse.ResponseData }
     * 
     */
    public RecordSummaryAuditResponse.ResponseData createRecordSummaryAuditResponseResponseData() {
        return new RecordSummaryAuditResponse.ResponseData();
    }

    /**
     * Create an instance of {@link API }
     * 
     */
    public API createAPI() {
        return new API();
    }

    /**
     * Create an instance of {@link AsyncSearchResult }
     * 
     */
    public AsyncSearchResult createAsyncSearchResult() {
        return new AsyncSearchResult();
    }

    /**
     * Create an instance of {@link AsyncTransactionInfo }
     * 
     */
    public AsyncTransactionInfo createAsyncTransactionInfo() {
        return new AsyncTransactionInfo();
    }

    /**
     * Create an instance of {@link BiographicData }
     * 
     */
    public BiographicData createBiographicData() {
        return new BiographicData();
    }

    /**
     * Create an instance of {@link BiographicDataInfo }
     * 
     */
    public BiographicDataInfo createBiographicDataInfo() {
        return new BiographicDataInfo();
    }

    /**
     * Create an instance of {@link BiometricItemInfo }
     * 
     */
    public BiometricItemInfo createBiometricItemInfo() {
        return new BiometricItemInfo();
    }

    /**
     * Create an instance of {@link CoreData }
     * 
     */
    public CoreData createCoreData() {
        return new CoreData();
    }

    /**
     * Create an instance of {@link DateItem }
     * 
     */
    public DateItem createDateItem() {
        return new DateItem();
    }

    /**
     * Create an instance of {@link DateItemInfo }
     * 
     */
    public DateItemInfo createDateItemInfo() {
        return new DateItemInfo();
    }

    /**
     * Create an instance of {@link DomainBiographicDataInfo }
     * 
     */
    public DomainBiographicDataInfo createDomainBiographicDataInfo() {
        return new DomainBiographicDataInfo();
    }

    /**
     * Create an instance of {@link DomainDateItemInfo }
     * 
     */
    public DomainDateItemInfo createDomainDateItemInfo() {
        return new DomainDateItemInfo();
    }

    /**
     * Create an instance of {@link DomainDescription }
     * 
     */
    public DomainDescription createDomainDescription() {
        return new DomainDescription();
    }

    /**
     * Create an instance of {@link DomainDoubleItemInfo }
     * 
     */
    public DomainDoubleItemInfo createDomainDoubleItemInfo() {
        return new DomainDoubleItemInfo();
    }

    /**
     * Create an instance of {@link DomainExtendedBinaryItemInfo }
     * 
     */
    public DomainExtendedBinaryItemInfo createDomainExtendedBinaryItemInfo() {
        return new DomainExtendedBinaryItemInfo();
    }

    /**
     * Create an instance of {@link DomainExtendedStringItemInfo }
     * 
     */
    public DomainExtendedStringItemInfo createDomainExtendedStringItemInfo() {
        return new DomainExtendedStringItemInfo();
    }

    /**
     * Create an instance of {@link DomainLongItemInfo }
     * 
     */
    public DomainLongItemInfo createDomainLongItemInfo() {
        return new DomainLongItemInfo();
    }

    /**
     * Create an instance of {@link DomainStringItemInfo }
     * 
     */
    public DomainStringItemInfo createDomainStringItemInfo() {
        return new DomainStringItemInfo();
    }

    /**
     * Create an instance of {@link DomainTimestampItemInfo }
     * 
     */
    public DomainTimestampItemInfo createDomainTimestampItemInfo() {
        return new DomainTimestampItemInfo();
    }

    /**
     * Create an instance of {@link DoubleItem }
     * 
     */
    public DoubleItem createDoubleItem() {
        return new DoubleItem();
    }

    /**
     * Create an instance of {@link DoubleItemInfo }
     * 
     */
    public DoubleItemInfo createDoubleItemInfo() {
        return new DoubleItemInfo();
    }

    /**
     * Create an instance of {@link ExtendedBinaryItem }
     * 
     */
    public ExtendedBinaryItem createExtendedBinaryItem() {
        return new ExtendedBinaryItem();
    }

    /**
     * Create an instance of {@link ExtendedBinaryItemInfo }
     * 
     */
    public ExtendedBinaryItemInfo createExtendedBinaryItemInfo() {
        return new ExtendedBinaryItemInfo();
    }

    /**
     * Create an instance of {@link ExtendedStringItem }
     * 
     */
    public ExtendedStringItem createExtendedStringItem() {
        return new ExtendedStringItem();
    }

    /**
     * Create an instance of {@link ExtendedStringItemInfo }
     * 
     */
    public ExtendedStringItemInfo createExtendedStringItemInfo() {
        return new ExtendedStringItemInfo();
    }

    /**
     * Create an instance of {@link ExternalMatcherIdentifier }
     * 
     */
    public ExternalMatcherIdentifier createExternalMatcherIdentifier() {
        return new ExternalMatcherIdentifier();
    }

    /**
     * Create an instance of {@link GroupIdentifier }
     * 
     */
    public GroupIdentifier createGroupIdentifier() {
        return new GroupIdentifier();
    }

    /**
     * Create an instance of {@link GroupMembership }
     * 
     */
    public GroupMembership createGroupMembership() {
        return new GroupMembership();
    }

    /**
     * Create an instance of {@link Identity }
     * 
     */
    public Identity createIdentity() {
        return new Identity();
    }

    /**
     * Create an instance of {@link IdentityDescription }
     * 
     */
    public IdentityDescription createIdentityDescription() {
        return new IdentityDescription();
    }

    /**
     * Create an instance of {@link IdentityIdentifier }
     * 
     */
    public IdentityIdentifier createIdentityIdentifier() {
        return new IdentityIdentifier();
    }

    /**
     * Create an instance of {@link Key }
     * 
     */
    public Key createKey() {
        return new Key();
    }

    /**
     * Create an instance of {@link KeyIdentifier }
     * 
     */
    public KeyIdentifier createKeyIdentifier() {
        return new KeyIdentifier();
    }

    /**
     * Create an instance of {@link LongItem }
     * 
     */
    public LongItem createLongItem() {
        return new LongItem();
    }

    /**
     * Create an instance of {@link LongItemInfo }
     * 
     */
    public LongItemInfo createLongItemInfo() {
        return new LongItemInfo();
    }

    /**
     * Create an instance of {@link MatchSummaryAudit }
     * 
     */
    public MatchSummaryAudit createMatchSummaryAudit() {
        return new MatchSummaryAudit();
    }

    /**
     * Create an instance of {@link MatcherIdentifier }
     * 
     */
    public MatcherIdentifier createMatcherIdentifier() {
        return new MatcherIdentifier();
    }

    /**
     * Create an instance of {@link Other }
     * 
     */
    public Other createOther() {
        return new Other();
    }

    /**
     * Create an instance of {@link Policy }
     * 
     */
    public Policy createPolicy() {
        return new Policy();
    }

    /**
     * Create an instance of {@link PolicyDescription }
     * 
     */
    public PolicyDescription createPolicyDescription() {
        return new PolicyDescription();
    }

    /**
     * Create an instance of {@link PolicyDetails }
     * 
     */
    public PolicyDetails createPolicyDetails() {
        return new PolicyDetails();
    }

    /**
     * Create an instance of {@link PolicyIdentifier }
     * 
     */
    public PolicyIdentifier createPolicyIdentifier() {
        return new PolicyIdentifier();
    }

    /**
     * Create an instance of {@link SampleScore }
     * 
     */
    public SampleScore createSampleScore() {
        return new SampleScore();
    }

    /**
     * Create an instance of {@link SearchAdjudicationDecision }
     * 
     */
    public SearchAdjudicationDecision createSearchAdjudicationDecision() {
        return new SearchAdjudicationDecision();
    }

    /**
     * Create an instance of {@link SearchRequestTrackingUID }
     * 
     */
    public SearchRequestTrackingUID createSearchRequestTrackingUID() {
        return new SearchRequestTrackingUID();
    }

    /**
     * Create an instance of {@link SearchTransactionIdentifier }
     * 
     */
    public SearchTransactionIdentifier createSearchTransactionIdentifier() {
        return new SearchTransactionIdentifier();
    }

    /**
     * Create an instance of {@link SecureEnvelope }
     * 
     */
    public SecureEnvelope createSecureEnvelope() {
        return new SecureEnvelope();
    }

    /**
     * Create an instance of {@link StringItem }
     * 
     */
    public StringItem createStringItem() {
        return new StringItem();
    }

    /**
     * Create an instance of {@link StringItemInfo }
     * 
     */
    public StringItemInfo createStringItemInfo() {
        return new StringItemInfo();
    }

    /**
     * Create an instance of {@link SummaryAuditIdentifier }
     * 
     */
    public SummaryAuditIdentifier createSummaryAuditIdentifier() {
        return new SummaryAuditIdentifier();
    }

    /**
     * Create an instance of {@link SummaryAuditSearchCriteria }
     * 
     */
    public SummaryAuditSearchCriteria createSummaryAuditSearchCriteria() {
        return new SummaryAuditSearchCriteria();
    }

    /**
     * Create an instance of {@link TimestampItem }
     * 
     */
    public TimestampItem createTimestampItem() {
        return new TimestampItem();
    }

    /**
     * Create an instance of {@link TimestampItemInfo }
     * 
     */
    public TimestampItemInfo createTimestampItemInfo() {
        return new TimestampItemInfo();
    }

    /**
     * Create an instance of {@link TypeQualifierInfo }
     * 
     */
    public TypeQualifierInfo createTypeQualifierInfo() {
        return new TypeQualifierInfo();
    }

    /**
     * Create an instance of {@link VerificationAdjudicationDecision }
     * 
     */
    public VerificationAdjudicationDecision createVerificationAdjudicationDecision() {
        return new VerificationAdjudicationDecision();
    }

    /**
     * Create an instance of {@link VerifyParameters.MatchThreshold }
     * 
     */
    public VerifyParameters.MatchThreshold createVerifyParametersMatchThreshold() {
        return new VerifyParameters.MatchThreshold();
    }

    /**
     * Create an instance of {@link VerificationAdjudication.SampleDecision }
     * 
     */
    public VerificationAdjudication.SampleDecision createVerificationAdjudicationSampleDecision() {
        return new VerificationAdjudication.SampleDecision();
    }

    /**
     * Create an instance of {@link SearchParameters.MatchThreshold }
     * 
     */
    public SearchParameters.MatchThreshold createSearchParametersMatchThreshold() {
        return new SearchParameters.MatchThreshold();
    }

    /**
     * Create an instance of {@link SearchAdjudication.SampleDecision }
     * 
     */
    public SearchAdjudication.SampleDecision createSearchAdjudicationSampleDecision() {
        return new SearchAdjudication.SampleDecision();
    }

    /**
     * Create an instance of {@link DomainDetails.Owner }
     * 
     */
    public DomainDetails.Owner createDomainDetailsOwner() {
        return new DomainDetails.Owner();
    }

    /**
     * Create an instance of {@link Candidate.CandidateScore }
     * 
     */
    public Candidate.CandidateScore createCandidateCandidateScore() {
        return new Candidate.CandidateScore();
    }

    /**
     * Create an instance of {@link BiometricDataElement.Data }
     * 
     */
    public BiometricDataElement.Data createBiometricDataElementData() {
        return new BiometricDataElement.Data();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractScore }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractScore }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/ws/de", name = "AbstractScore")
    public JAXBElement<AbstractScore> createAbstractScore(AbstractScore value) {
        return new JAXBElement<AbstractScore>(_AbstractScore_QNAME, AbstractScore.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FMR }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FMR }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/ws/de", name = "FMR")
    public JAXBElement<FMR> createFMR(FMR value) {
        return new JAXBElement<FMR>(_FMR_QNAME, FMR.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RawScore }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RawScore }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.daon.com/ws/de", name = "RawScore")
    public JAXBElement<RawScore> createRawScore(RawScore value) {
        return new JAXBElement<RawScore>(_RawScore_QNAME, RawScore.class, null, value);
    }

}
