//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.17 at 02:10:31 PM ART 
//


package ar.com.macro.validacion.model.client.daonengine.systemmanagement.dto.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for SearchParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchParameters"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CandidateListSize" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="MatchThreshold" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;double"&gt;
 *                 &lt;attribute name="PossibleMatchThreshold" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchParameters", propOrder = {
    "candidateListSize",
    "matchThreshold"
})
public class SearchParameters {

    @XmlElement(name = "CandidateListSize")
    protected Integer candidateListSize;
    @XmlElement(name = "MatchThreshold")
    protected SearchParameters.MatchThreshold matchThreshold;

    /**
     * Gets the value of the candidateListSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCandidateListSize() {
        return candidateListSize;
    }

    /**
     * Sets the value of the candidateListSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCandidateListSize(Integer value) {
        this.candidateListSize = value;
    }

    /**
     * Gets the value of the matchThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link SearchParameters.MatchThreshold }
     *     
     */
    public SearchParameters.MatchThreshold getMatchThreshold() {
        return matchThreshold;
    }

    /**
     * Sets the value of the matchThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchParameters.MatchThreshold }
     *     
     */
    public void setMatchThreshold(SearchParameters.MatchThreshold value) {
        this.matchThreshold = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;double"&gt;
     *       &lt;attribute name="PossibleMatchThreshold" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class MatchThreshold {

        @XmlValue
        protected double value;
        @XmlAttribute(name = "PossibleMatchThreshold")
        protected Double possibleMatchThreshold;

        /**
         * Gets the value of the value property.
         * 
         */
        public double getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(double value) {
            this.value = value;
        }

        /**
         * Gets the value of the possibleMatchThreshold property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getPossibleMatchThreshold() {
            return possibleMatchThreshold;
        }

        /**
         * Sets the value of the possibleMatchThreshold property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setPossibleMatchThreshold(Double value) {
            this.possibleMatchThreshold = value;
        }

    }

}
