//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.17 at 02:10:31 PM ART 
//


package ar.com.macro.validacion.model.client.daonengine.systemmanagement.dto.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A secure envelope - contains secure data. The data is
 *     			encrypted via a session Key. The session Key itself is
 *     			encrypted using the current private information Key.
 * 
 * <p>Java class for SecureEnvelope complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SecureEnvelope"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.daon.com/ws/de}AbstractSecureDetails"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SecureData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SecureEnvelope", propOrder = {
    "secureData"
})
public class SecureEnvelope
    extends AbstractSecureDetails
{

    @XmlElement(name = "SecureData", required = true)
    protected byte[] secureData;

    /**
     * Gets the value of the secureData property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getSecureData() {
        return secureData;
    }

    /**
     * Sets the value of the secureData property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setSecureData(byte[] value) {
        this.secureData = value;
    }

}
