//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.17 at 02:10:31 PM ART 
//


package ar.com.macro.validacion.model.client.daonengine.systemmanagement.dto.soap;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SummaryAuditOrderByField.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SummaryAuditOrderByField"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="IDENTITY_IDENTIFIER"/&gt;
 *     &lt;enumeration value="CREATED_DTM"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SummaryAuditOrderByField")
@XmlEnum
public enum SummaryAuditOrderByField {


    /**
     * Identity Identifier associated 
     *                    	with the summary audit record.
     *                    	Note that this field may be empty 
     *                    	for some records.
     * 
     */
    IDENTITY_IDENTIFIER,

    /**
     * The date and time at which the 
     *                     summary audit record was created.
     * 
     */
    CREATED_DTM;

    public String value() {
        return name();
    }

    public static SummaryAuditOrderByField fromValue(String v) {
        return valueOf(v);
    }

}
