//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.08 at 01:37:27 PM PET 
//


package ar.com.macro.enrolamiento.model.client.renaper.dto.soap;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for consultaPorTCNResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="consultaPorTCNResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="salida" type="{urn:mininteriorwsdl}salida"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consultaPorTCNResponse", propOrder = {

})
@XmlRootElement(name = "consultaPorTCNResponse")
public class ConsultaPorTCNResponse {

    @XmlElement(required = true)
    protected Salida salida;

    /**
     * Gets the value of the salida property.
     * 
     * @return
     *     possible object is
     *     {@link Salida }
     *     
     */
    public Salida getSalida() {
        return salida;
    }

    /**
     * Sets the value of the salida property.
     * 
     * @param value
     *     allowed object is
     *     {@link Salida }
     *     
     */
    public void setSalida(Salida value) {
        this.salida = value;
    }

}
